# Pandas Assignment: 

## Files Required
Place the following CSV files in the same directory as this notebook (or update the paths in the load cell):
- sy_account_20251225_155056.csv
- ab_user_20251225_155056.csv
- sy_app_module_20251225_155056.csv
- sy_application_20251225_155056.csv
- in_model_20251225_155056.csv
- in_workspace_20251225_155056.csv
- in_timeseries_version_20251225_155057.csv
- in_material_20251225_155057.csv
- in_resource_20251225_155057.csv
- in_time_dimension_20251225_155057.csv
- in_timeseries_20251225_155057.csv
- in_timeseries_data_20251225_155101.csv

> **Note:** Run the import & load cells first. Each solution cell saves its output to a variable (e.g., `q01_result`).


In [1]:
# Necessary libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Display options for better readability (optional)
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)


In [2]:
# Read all files here

ab_user=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\ab_user_20251225_155056.csv")
in_material=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_material_20251225_155057.csv")
in_model=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_model_20251225_155056.csv")
in_resource=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_resource_20251225_155057.csv")
in_time_dimension=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_time_dimension_20251225_155057.csv")
in_timeseries=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_timeseries_20251225_155057.csv")
in_timeseries_data=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_timeseries_data_20251225_155101.csv")
in_timeseries_version=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_timeseries_version_20251225_155057.csv")
in_workspace=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_workspace_20251225_155056.csv")
sy_account=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\sy_account_20251225_155056.csv")
sy_app_module=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\sy_app_module_20251225_155056.csv")
sy_application=pd.read_csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\sy_application_20251225_155056.csv")

**Q1.** Retrieve all columns from the `sy_account` table.

In [3]:
sy_account.columns

Index(['id', 'name'], dtype='object')

**Q2.** Find all users from the `ab_user` table where `account_id = 3`.

In [4]:
ab_user[ab_user["account_id"]==3]

Empty DataFrame
Columns: [id, username, account_id]
Index: []

**Q3.** Display all application modules from `sy_app_module` ordered by `app_name` in ascending order.

In [5]:
sy_app_module.sort_values(by="app_name",ascending=True)

app_id  application_id app_code               app_name
2      14               3     xsfc  Radar-Demand Planning
1       6               2     xpnp           Trinity-S&OP
0      19               5     xbds    XBridge-Integration

**Q4.** Fetch the first 10 records from the `in_timeseries_data` table.

In [6]:
in_timeseries_data.head(10)

ts_data_id  ts_id               dttime       data  version_id
0    44471796  27902  2020-10-01 00:00:00  10549.207         130
1    44471774  27902  2018-12-01 00:00:00  11513.370         130
2    44471775  27902  2019-01-01 00:00:00  11556.125         130
3    44471776  27902  2019-02-01 00:00:00  11598.547         130
4    44471777  27902  2019-03-01 00:00:00  11643.222         130
5    44471778  27902  2019-04-01 00:00:00  11687.960         130
6    44471779  27902  2019-05-01 00:00:00  11732.147         130
7    44471780  27902  2019-06-01 00:00:00  11775.567         130
8    44471781  27902  2019-07-01 00:00:00  11820.099         130
9    44471782  27902  2019-08-01 00:00:00  11863.516         130

**Q5.** Count the total number of materials in `in_material` for `workspace_id = 53`.

In [7]:
in_material[in_material["workspace_id"]==53].size

57

**Q6.** Display all users from `ab_user` ordered by `username` in ascending order.

In [8]:
ab_user.sort_values(by="username",ascending=True)

id     username  account_id
0   1        admin           1
3   5   customer_1           1
1   3  hetal.patel           1
4   7     pratik.m           1
2   4         ravi           1

**Q7.** Find all timeseries from `in_material` where `workspace_id = 53` and `material_id = 83498`.

In [9]:
in_material[(in_material["workspace_id"]==53) & (in_material["material_id"]==83498)]

material_id material_name  workspace_id
1        83498        MS Reg            53

**Q8.** Retrieve all versions from `in_timeseries_version` where `version_id` is 125, 126, or 130.

In [10]:
in_timeseries_version[in_timeseries_version["version_id"].isin([125,126,130])]

version_id        version_name  modified_by               modified_time
0         125                 Raw            1  2022-05-05 13:11:52.265578
1         126  Manually Corrected            1  2022-05-05 13:11:52.271739
2         130         Forecast-MA            1  2022-05-11 09:49:50.393995

**Q9.** Retrieve the first 5 materials from `in_material` where `workspace_id = 53`, ordered by `material_name`.

In [11]:
in_material[in_material["workspace_id"]==53].sort_values(by="material_name",ascending=False).head(5)

material_id material_name  workspace_id
11        83508           XYZ            53
9         83506       Regular            53
10        83507       Premium            53
15        83512          MS95            53
14        83511          MS92            53

**Q10.** Count the total number of users in the `ab_user` table.

In [12]:
ab_user.shape[0]

5

In [13]:
len(ab_user)

5

**Q11.** Calculate the sum of all `data` values from `in_timeseries_data` where `version_id = 125`.

In [14]:
df=in_timeseries_data[in_timeseries_data["version_id"]==125]
df["data"].sum()

np.float64(118863246.23341441)

**Q12.** Find the average value of `data` from `in_timeseries_data` where `version_id = 125`.

In [15]:
df=in_timeseries_data[in_timeseries_data["version_id"]==125]
print("Avg:",df["data"].mean())

Avg: 4571.663316669785


**Q13.** Find the maximum and minimum `data` values from `in_timeseries_data` where `version_id = 130`.

In [16]:
df=in_timeseries_data[in_timeseries_data["version_id"]==130]
print("Min:",df["data"].min())
print("Max:",df["data"].max())

Min: 0.0
Max: 79575.234


**Q14.** Count the number of timeseries records grouped by `material_id` from `in_timeseries`.

In [17]:
in_timeseries.groupby("material_id").count()

ts_id  geography_id  time_level_id
material_id                                    
83498          100           100            100
83499          100           100            100
83500          100           100            100
83501          100           100            100
83502          100           100            100
83503          100           100            100
83504          100           100            100
83505          100           100            100
83506            1             1              1
83507            1             1              1
83508            1             1              1

**Q15.** Count the number of users grouped by `account_id` where `account_id` is not null.

In [18]:
ab_user[ab_user["account_id"].notna()].groupby("account_id").size().reset_index(name="user_count")



account_id  user_count
0           1           5

**Q16.** Display `version_id`, total record count, and average `data` value grouped by `version_id` from `in_timeseries_data` where `version_id = 125`.

In [19]:
in_timeseries_data[in_timeseries_data["version_id"] == 125].groupby("version_id")\
    .agg(total_record_count=("version_id", "count"),avg_data=("data", "mean")).reset_index()

version_id  total_record_count     avg_data
0         125               26000  4571.663317

**Q17.** Find all `material_id` values that have more than 3 timeseries records.

In [20]:
df=in_timeseries.groupby("material_id").size().reset_index(name="count")
df[df["count"]>3]

material_id  count
0        83498    100
1        83499    100
2        83500    100
3        83501    100
4        83502    100
5        83503    100
6        83504    100
7        83505    100

**Q18.** Count the number of timeseries data records grouped by both `version_id` and `ts_id` where `version_id= 53`, and show only those with `count > 1`.

In [21]:
in_timeseries_data[in_timeseries_data["version_id"] ==125] \
                .groupby(["version_id", "ts_id"]).size().reset_index(name="count").query("count > 1")


version_id  ts_id  count
0           125  27363     52
1           125  27364     52
2           125  27365     52
3           125  27366     52
4           125  27367     52
..          ...    ...    ...
495         125  27858     52
496         125  27859     52
497         125  27860     52
498         125  27861     52
499         125  27862     52

[500 rows x 3 columns]

**Q19.** Display `username` along with account name. Output columns: `id`, `username`, `account_id`, `name`.

In [22]:
ab_user.merge(sy_account,on="id",how="inner")[["id", "username", "account_id", "name"]]

id     username  account_id                 name
0   1        admin           1         ESPL_Account
1   3  hetal.patel           1                Enpro
2   4         ravi           1           Indian Oil
3   5   customer_1           1  Standard Automotive

**Q20.** Show all application names and their corresponding application module details. Output columns: `app_id`, `app_code`, `app_name`, `application_id`, `application_name`.

In [23]:
sy_application.merge(sy_app_module,on="application_id",how="outer")[["app_id", "app_code", "app_name", "application_id","application_name"]]

app_id app_code               app_name  application_id application_name
0     NaN      NaN                    NaN               1              XML
1     6.0     xpnp           Trinity-S&OP               2            XPlan
2    14.0     xsfc  Radar-Demand Planning               3           XSight
3    19.0     xbds    XBridge-Integration               5          XBridge

**Q21.** Retrieve model names along with their associated application names. Output columns: `model_id`, `model_name`, `application_id`, `application_name`.

In [24]:
in_model.merge(sy_application,on="application_id",how="left")[["model_id","model_name","application_id","application_name"]]

model_id   model_name  application_id application_name
0        29  Oil and Gas               3           XSight

**Q22.** Display workspace names with their corresponding model names. Output columns: `workspace_id`, `workspace_name`, `model_id`, `model_name`.

In [25]:
in_workspace.merge(in_model,on="model_id",how="left")[["workspace_id","workspace_name","model_id","model_name"]]

workspace_id workspace_name  model_id   model_name
0            53         Nayara        29  Oil and Gas

**Q23.** Show all version names along with their workspace names where `workspace_id = 53`. Output columns: `version_id`, `version_name`, `workspace_id`, `workspace_name`.

In [26]:
in_workspace[in_workspace["workspace_id"] == 53].merge(in_timeseries_version, how="cross")[["version_id", "version_name", "workspace_id", "workspace_name"]]



version_id        version_name  workspace_id workspace_name
0         125                 Raw            53         Nayara
1         126  Manually Corrected            53         Nayara
2         130         Forecast-MA            53         Nayara
3         135    Forecast-Bestfit            53         Nayara

**Q24.** Display material names with their workspace names. Output columns: `material_id`, `material_name`, `workspace_id`, `workspace_name`.

In [27]:
in_material.merge(in_workspace,on="workspace_id",how="left")[["material_id","material_name","workspace_id","workspace_name"]]

material_id  material_name  workspace_id workspace_name
0         83515        LB20W40            53         Nayara
1         83498         MS Reg            53         Nayara
2         83499        MS Prem            53         Nayara
3         83500        HSD Reg            53         Nayara
4         83501       HSD Prem            53         Nayara
5         83502  Lube20w40 XYZ            53         Nayara
6         83503       Gasoline            53         Nayara
7         83504         Diesel            53         Nayara
8         83505      Auto Lube            53         Nayara
9         83506        Regular            53         Nayara
10        83507        Premium            53         Nayara
11        83508            XYZ            53         Nayara
12        83509           Fuel            53         Nayara
13        83510     Lubricants            53         Nayara
14        83511           MS92            53         Nayara
15        83512           MS95            53         Nayara
16        83513           HSDR            53         Nayara
17        83514          HSDRP            53         Nayara
18        83516            All            53         Nayara

**Q25.** Show resource (geography) names along with their workspace names where `workspace_id = 53`. Output columns: `resource_id`, `resource_name`, `workspace_id`, `workspace_name`.

In [28]:
in_resource.merge(in_workspace,on="workspace_id",how="inner")[["geography_id","resource_name","workspace_id","workspace_name"]].head()

geography_id         resource_name  workspace_id workspace_name
0         30113    Elhaam Corporation            53         Nayara
1         30114   Yashkalgi Petroleum            53         Nayara
2         30115    Sukhmani Petroleum            53         Nayara
3         30116  Vrajpari Corporation            53         Nayara
4         30117  Sai Shakti Petroleum            53         Nayara

**Q26.** Display time dimension names with their associated workspace names. Output columns: `time_dimension_id`, `time_dimension_name`, `workspace_id`, `workspace_name`.

In [29]:
in_time_dimension.merge(in_workspace,on="workspace_id",how="inner").rename(columns={"time_level_id": "time_dimension_id"}) \
                 [["time_dimension_id","time_dimension_name", "workspace_id","workspace_name"]]

time_dimension_id time_dimension_name  workspace_id workspace_name
0                 64             Quarter            53         Nayara
1                 65                Year            53         Nayara
2                 63               Month            53         Nayara

**Q27.** Show timeseries IDs along with their corresponding material names where `workspace_id = 53`. Output columns: `ts_id`, `material_id`, `material_name`, `workspace_id`.

In [30]:
in_timeseries.merge(in_material,on="material_id",how="inner")[["ts_id","material_id","material_name","workspace_id"]]

ts_id  material_id  material_name  workspace_id
0    27803        83498         MS Reg            53
1    27804        83499        MS Prem            53
2    27805        83500        HSD Reg            53
3    27806        83501       HSD Prem            53
4    27807        83502  Lube20w40 XYZ            53
..     ...          ...            ...           ...
798  28299        83504         Diesel            53
799  28300        83503       Gasoline            53
800  28301        83505      Auto Lube            53
801  28302        83504         Diesel            53
802  28303        83503       Gasoline            53

[803 rows x 4 columns]

**Q28.** Display timeseries data along with their version names where `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `version_name`.

in_timeseries_data
→ in_timeseries        (ts_id)
→ in_resource          (geography_id → workspace_id)
→ in_timeseries_version (version_id)


In [31]:
in_timeseries_data.merge(in_timeseries, on="ts_id", how="inner") \
                  .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner") \
                  .merge(in_timeseries_version,on="version_id",how="inner") \
                  [["ts_data_id", "ts_id", "dttime", "data", "version_id", "version_name"]]


ts_data_id  ts_id               dttime        data  version_id  \
0        44471796  27902  2020-10-01 00:00:00  10549.2070         130   
1        44471774  27902  2018-12-01 00:00:00  11513.3700         130   
2        44471775  27902  2019-01-01 00:00:00  11556.1250         130   
3        44471776  27902  2019-02-01 00:00:00  11598.5470         130   
4        44471777  27902  2019-03-01 00:00:00  11643.2220         130   
...           ...    ...                  ...         ...         ...   
26229    43185353  27509  2022-02-01 00:00:00   4410.5530         125   
26230    43185354  27509  2022-01-01 00:00:00   4414.9590         125   
26231    43185355  27509  2021-12-01 00:00:00   4105.9120         125   
26232    43185356  27509  2021-11-01 00:00:00   4105.9120         125   
26233    43185357  27509  2021-10-01 00:00:00   4089.5212         125   

      version_name  
0      Forecast-MA  
1      Forecast-MA  
2      Forecast-MA  
3      Forecast-MA  
4      Forecast-MA  
...            ...  
26229          Raw  
26230          Raw  
26231          Raw  
26232          Raw  
26233          Raw  

[26234 rows x 6 columns]

**Q29.** Show all users and their account names where `account_id > 1`. Output columns: `id`, `username`, `account_id`, `name`.

In [32]:
ab_user.merge(sy_account,on="id",how="inner")[["id","username","account_id","name"]]

id     username  account_id                 name
0   1        admin           1         ESPL_Account
1   3  hetal.patel           1                Enpro
2   4         ravi           1           Indian Oil
3   5   customer_1           1  Standard Automotive

**Q30.** Display application module names along with their application descriptions. Output columns: `app_id`, `app_name`, `application_id`, `application_name`, `application_description`.



In [33]:
in_model.merge(sy_application,on="application_id",how="inner")\
        .merge(sy_app_module,on="application_id",how="inner").rename(columns={"app_id_x":"app_id"}) \
        [["app_id", "app_name", "application_id", "application_name", "application_description"]]




app_id               app_name  application_id application_name  \
0      14  Radar-Demand Planning               3           XSight   

                             application_description  
0  XSoght: Predictive Analytics. Serves Forecasti...

**Q31.** Show model names and their descriptions along with the application module name. Output columns: `model_id`, `model_name`, `model_description`, `app_id`, `app_name`.

In [34]:
in_model.merge(sy_app_module,on="application_id",how="inner")[["model_id","model_name","model_description","app_id_x","app_name"]]

model_id   model_name   model_description  app_id_x               app_name
0        29  Oil and Gas  Oil and Gas Sector        14  Radar-Demand Planning

**Q32.** Show workspace name, model name, and application name for `workspace_id = 53`. Output columns: `workspace_id`, `workspace_name`, `model_id`, `model_name`, `application_id`, `application_name`.

In [35]:
in_workspace[in_workspace["workspace_id"]==53].merge(in_model,on="model_id",how="inner") \
                                            .merge(sy_application,on="application_id",how="inner") \
                                            [["workspace_id","workspace_name","model_id","model_name","application_id","application_name"]]

workspace_id workspace_name  model_id   model_name  application_id  \
0            53         Nayara        29  Oil and Gas               3   

  application_name  
0           XSight

**Q33.** Display timeseries ID, material name, geography name, and time dimension name for `workspace_id = 53`. Output columns: `ts_id`, `material_id`, `material_name`, `resource_id`, `resource_name`, `time_dimension_id`, `time_dimension_name`.

In [36]:
in_material[in_material["workspace_id"]==53].merge(in_timeseries,on="material_id",how="inner") \
        .merge(in_resource,on="workspace_id",how="inner") \
        .merge(in_time_dimension,on="workspace_id",how="inner") \
        [["ts_id","material_id","material_name","geography_id_x","resource_name","time_level_id_x","time_dimension_name"]]

ts_id  material_id material_name  geography_id_x        resource_name  \
0       27803        83498        MS Reg           30201   Elhaam Corporation   
1       27803        83498        MS Reg           30201   Elhaam Corporation   
2       27803        83498        MS Reg           30201   Elhaam Corporation   
3       27803        83498        MS Reg           30201  Yashkalgi Petroleum   
4       27803        83498        MS Reg           30201  Yashkalgi Petroleum   
...       ...          ...           ...             ...                  ...   
476977  27904        83508           XYZ           30213                 Kota   
476978  27904        83508           XYZ           30213                 Kota   
476979  27904        83508           XYZ           30213              Bhiwadi   
476980  27904        83508           XYZ           30213              Bhiwadi   
476981  27904        83508           XYZ           30213              Bhiwadi   

        time_level_id_x time_dimension_name  
0                     5             Quarter  
1                     5                Year  
2                     5               Month  
3                     5             Quarter  
4                     5                Year  
...                 ...                 ...  
476977                5                Year  
476978                5               Month  
476979                5             Quarter  
476980                5                Year  
476981                5               Month  

[476982 rows x 7 columns]

**Q34.** Display timeseries data value, material name, geography name, and version name where `workspace_id = 53` and `version_id = 125`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `material_id`, `material_name`, `resource_id`, `resource_name`, `version_id`, `version_name`.

in_timeseries_data
→ in_timeseries          (ts_id)
→ in_material            (material_id)
→ in_resource            (geography_id → resource_id, workspace_id)
→ in_timeseries_version  (version_id)


In [37]:
in_timeseries_data.merge(in_timeseries, on="ts_id", how="inner").merge(in_material,on="material_id",how="inner") \
                .merge(in_resource[(in_resource["workspace_id"] == 53)],on="geography_id",how="inner")  \
                    .merge(in_timeseries_version[in_timeseries_version["version_id"] == 125],on="version_id",how="inner")\
                        [["ts_data_id","ts_id","dttime","data","material_id","material_name","geography_id","resource_name","version_id","version_name"]]



ts_data_id  ts_id               dttime        data  material_id  \
0        43177824  27364  2019-04-01 00:00:00   381.43152        83499   
1        43177754  27363  2020-10-01 00:00:00  2041.82030        83498   
2        43177755  27363  2020-09-01 00:00:00  1921.83700        83498   
3        43177756  27363  2020-08-01 00:00:00  1991.69370        83498   
4        43177757  27363  2020-07-01 00:00:00  1933.89040        83498   
...           ...    ...                  ...         ...          ...   
25995    43185353  27509  2022-02-01 00:00:00  4410.55300        83499   
25996    43185354  27509  2022-01-01 00:00:00  4414.95900        83499   
25997    43185355  27509  2021-12-01 00:00:00  4105.91200        83499   
25998    43185356  27509  2021-11-01 00:00:00  4105.91200        83499   
25999    43185357  27509  2021-10-01 00:00:00  4089.52120        83499   

      material_name  geography_id         resource_name  version_id  \
0           MS Prem         30113    Elhaam Corporation         125   
1            MS Reg         30113    Elhaam Corporation         125   
2            MS Reg         30113    Elhaam Corporation         125   
3            MS Reg         30113    Elhaam Corporation         125   
4            MS Reg         30113    Elhaam Corporation         125   
...             ...           ...                   ...         ...   
25995       MS Prem         30142  Balaji Nayara Energy         125   
25996       MS Prem         30142  Balaji Nayara Energy         125   
25997       MS Prem         30142  Balaji Nayara Energy         125   
25998       MS Prem         30142  Balaji Nayara Energy         125   
25999       MS Prem         30142  Balaji Nayara Energy         125   

      version_name  
0              Raw  
1              Raw  
2              Raw  
3              Raw  
4              Raw  
...            ...  
25995          Raw  
25996          Raw  
25997          Raw  
25998          Raw  
25999          Raw  

[26000 rows x 10 columns]

**Q35.** Show the latest 10 timeseries records (by datetime descending) for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `material_name`, `resource_name`, `time_dimension_name`, `version_name`, `workspace_name`.

in_timeseries_data
→ in_timeseries
→ in_material
→ in_resource        (workspace filter)
→ in_time_dimension
→ in_timeseries_version
→ in_workspace

In [38]:
in_timeseries_data.merge(in_timeseries, on="ts_id", how="inner") \
    .merge(in_material, on="material_id", how="inner")  \
    .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id", how="inner") \
    .merge(in_time_dimension, on="time_level_id", how="inner") \
    .merge(in_timeseries_version, on="version_id", how="inner") \
    .merge(in_workspace, on="workspace_id", how="inner") \
    .sort_values("dttime", ascending=False).head(10)  \
    [["ts_data_id","ts_id","dttime","data","material_name","resource_name","time_dimension_name","version_name","workspace_name"]]



Empty DataFrame
Columns: [ts_data_id, ts_id, dttime, data, material_name, resource_name, time_dimension_name, version_name, workspace_name]
Index: []

**Q36.** Assign a row number to each timeseries data record within `version_id =125`, ordered by `dttime`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `row_num`.

In [48]:
df = ( in_timeseries_data.loc[in_timeseries_data["version_id"] == 125,["ts_data_id", "ts_id", "dttime", "data", "version_id"]] \
    .sort_values("dttime").reset_index(drop=True))

df["row_num"] = df.index + 1 
df


ts_data_id  ts_id               dttime         data  version_id  \
0        43197850  27749  2018-01-01 00:00:00  4093.899200         125   
1        43186509  27531  2018-01-01 00:00:00   491.891400         125   
2        43186561  27532  2018-01-01 00:00:00    62.653500         125   
3        43182665  27457  2018-01-01 00:00:00   213.095340         125   
4        43186670  27534  2018-01-01 00:00:00   604.971400         125   
...           ...    ...                  ...          ...         ...   
25995    43180128  27409  2022-04-01 00:00:00  1095.688100         125   
25996    43196379  27721  2022-04-01 00:00:00  1660.989400         125   
25997    43202811  27845  2022-04-01 00:00:00  1238.538100         125   
25998    43183984  27483  2022-04-01 00:00:00  2428.254200         125   
25999    43191985  27637  2022-04-01 00:00:00     7.732935         125   

       row_num  
0            1  
1            2  
2            3  
3            4  
4            5  
...        ...  
25995    25996  
25996    25997  
25997    25998  
25998    25999  
25999    26000  

[26000 rows x 6 columns]

**Q37.** Rank timeseries data values within each `version_id` for `workspace_id = 53`, ordered by `data` value descending. Output columns: `ts_data_id`, `ts_id`, `data`, `version_id`, `rank`.

in_timeseries_data
→ in_timeseries      (ts_id → version_id, geography_id)
→ in_resource        (geography_id → workspace_id)


In [ ]:
df=(in_timeseries_data.merge(in_timeseries,on="ts_id",how="inner")  \
                      .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner")  ) 

df ["rank"] = (df.groupby("version_id")["data"].rank(method="dense", ascending=False))

df.sort_values("rank")[["ts_data_id","ts_id","data","version_id","rank"]]

ts_data_id  ts_id          data  version_id     rank
7839    43185388  27510  50131.637000         125      1.0
62      44472310  27903  79575.234000         130      1.0
61      44472309  27903  79290.730000         130      2.0
7841    43185390  27510  49662.305000         125      2.0
7840    43185389  27510  48988.640000         125      3.0
...          ...    ...           ...         ...      ...
1263    43179772  27402      1.301625         125  15790.0
1268    43179777  27402      1.300323         125  15791.0
1270    43179779  27402      1.299022         125  15792.0
1269    43179778  27402      1.299022         125  15792.0
1274    43179783  27402      1.299022         125  15792.0

[26234 rows x 5 columns]

**Q38.** Calculate the running total (cumulative sum) of `data` values for each `ts_id`, ordered by `dttime`, for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `running_total`.

in_timeseries_data
→ in_timeseries      (ts_id → version_id, geography_id)
→ in_resource        (geography_id → workspace_id)


In [56]:
result = in_timeseries_data.merge(in_timeseries,on="ts_id", how="inner") \
           .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner") \
           .sort_values(["ts_id", "dttime"]) 

result["running_total"] = result.groupby("ts_id")["data"].cumsum()

result[["ts_data_id","ts_id","dttime","data","version_id","running_total"]]

ts_data_id  ts_id               dttime       data  version_id  \
268    43177787  27363  2018-01-01 00:00:00  2915.9478         125   
267    43177786  27363  2018-02-01 00:00:00  2846.3586         125   
266    43177785  27363  2018-03-01 00:00:00  3013.9375         125   
265    43177784  27363  2018-04-01 00:00:00  2057.4304         125   
264    43177783  27363  2018-05-01 00:00:00  2129.4080         125   
..          ...    ...                  ...        ...         ...   
150    44472893  27904  2025-01-01 00:00:00     0.0000         130   
151    44472894  27904  2025-02-01 00:00:00     0.0000         130   
152    44472895  27904  2025-03-01 00:00:00     0.0000         130   
153    44472896  27904  2025-04-01 00:00:00     0.0000         130   
154    44472897  27904  2025-05-01 00:00:00     0.0000         130   

     running_total  
268      2915.9478  
267      5762.3064  
266      8776.2439  
265     10833.6743  
264     12963.0823  
..             ...  
150     36690.3882  
151     36690.3882  
152     36690.3882  
153     36690.3882  
154     36690.3882  

[26234 rows x 6 columns]

**Q39.** Find the previous and next `data` values for each timeseries record ordered by `dttime`, where `workspace_id = 53` and `version_id = 125`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `previous_value`, `next_value`.

in_timeseries_data
→ in_timeseries      (ts_id → version_id, geography_id)
→ in_resource        (geography_id → workspace_id)


In [63]:
result =in_timeseries_data.merge(in_timeseries,on="ts_id",how="inner")  \
           .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner")

result = result[result["version_id"] == 125].sort_values(["ts_id", "dttime"])

result["previous_value"] = result.groupby("ts_id")["data"].shift(1)
result["next_value"] = result.groupby("ts_id")["data"].shift(-1)

result.sort_index()[["ts_data_id","ts_id","dttime","data","previous_value","next_value"]]




ts_data_id  ts_id               dttime        data  previous_value  \
234      43177824  27364  2019-04-01 00:00:00   381.43152       381.43152   
235      43177754  27363  2020-10-01 00:00:00  2041.82030      1921.83700   
236      43177755  27363  2020-09-01 00:00:00  1921.83700      1991.69370   
237      43177756  27363  2020-08-01 00:00:00  1991.69370      1933.89040   
238      43177757  27363  2020-07-01 00:00:00  1933.89040      1984.34690   
...           ...    ...                  ...         ...             ...   
26229    43185353  27509  2022-02-01 00:00:00  4410.55300      4414.95900   
26230    43185354  27509  2022-01-01 00:00:00  4414.95900      4105.91200   
26231    43185355  27509  2021-12-01 00:00:00  4105.91200      4105.91200   
26232    43185356  27509  2021-11-01 00:00:00  4105.91200      4089.52120   
26233    43185357  27509  2021-10-01 00:00:00  4089.52120      4093.61900   

       next_value  
234      381.0501  
235     2039.8845  
236     2041.8203  
237     1921.8370  
238     1991.6937  
...           ...  
26229   4414.9590  
26230   4410.5530  
26231   4414.9590  
26232   4105.9120  
26233   4105.9120  

[26000 rows x 6 columns]

**Q40.** Calculate the moving average of `data` values over the last 3 records (including current) for each timeseries ordered by `dttime`, where `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `moving_avg_3`.

in_timeseries_data
→ in_timeseries      (ts_id → geography_id)
→ in_resource        (geography_id → workspace_id)


In [61]:
result =in_timeseries_data.merge(in_timeseries,on="ts_id",how="inner")  \
            .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner")  \
            .sort_values(["ts_id", "dttime"])

result["moving_avg_3"] = result.groupby("ts_id")["data"].rolling(window=3, min_periods=1).mean().reset_index(level=0, drop=True)

result.sort_index()[["ts_data_id", "ts_id", "dttime", "data", "moving_avg_3"]]


ts_data_id  ts_id               dttime        data  moving_avg_3
0        44471796  27902  2020-10-01 00:00:00  10549.2070  10697.535000
1        44471774  27902  2018-12-01 00:00:00  11513.3700  11513.370000
2        44471775  27902  2019-01-01 00:00:00  11556.1250  11534.747500
3        44471776  27902  2019-02-01 00:00:00  11598.5470  11556.014000
4        44471777  27902  2019-03-01 00:00:00  11643.2220  11599.298000
...           ...    ...                  ...         ...           ...
26229    43185353  27509  2022-02-01 00:00:00   4410.5530   4310.474667
26230    43185354  27509  2022-01-01 00:00:00   4414.9590   4208.927667
26231    43185355  27509  2021-12-01 00:00:00   4105.9120   4100.448400
26232    43185356  27509  2021-11-01 00:00:00   4105.9120   4096.350733
26233    43185357  27509  2021-10-01 00:00:00   4089.5212   4096.350733

[26234 rows x 5 columns]

**Q41.** Assign a dense rank to materials based on the count of their timeseries records in `workspace_id = 53`. Output columns: `material_id`, `timeseries_count`, `dense_rank`.

in_timeseries_data
→ in_timeseries      (ts_id → material_id, geography_id)
→ in_resource        (geography_id → workspace_id)


In [65]:
df =in_timeseries_data.merge(in_timeseries,on="ts_id",how="inner")  \
        .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner") 

material_counts = df.groupby("material_id").size().reset_index(name="timeseries_count")

material_counts["dense_rank"] =material_counts["timeseries_count"].rank(method="dense", ascending=False)

material_counts

material_id  timeseries_count  dense_rank
0        83498              5200         1.0
1        83499              5200         1.0
2        83500              5200         1.0
3        83501              5200         1.0
4        83502              5200         1.0
5        83506                78         2.0
6        83507                78         2.0
7        83508                78         2.0

**Q42.** Partition timeseries data by `version_id` and display the maximum `data` value within each version for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `max_in_version`.

in_timeseries_data
→ in_timeseries      (ts_id → version_id, geography_id)
→ in_resource        (geography_id → workspace_id)


In [66]:
result = (in_timeseries_data.merge(in_timeseries,on="ts_id",how="inner")
            .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner")  )

result["max_in_version"] = (result.groupby("version_id")["data"].transform("max"))

result[["ts_data_id","ts_id","dttime","data","version_id","max_in_version"]]

ts_data_id  ts_id               dttime        data  version_id  \
0        44471796  27902  2020-10-01 00:00:00  10549.2070         130   
1        44471774  27902  2018-12-01 00:00:00  11513.3700         130   
2        44471775  27902  2019-01-01 00:00:00  11556.1250         130   
3        44471776  27902  2019-02-01 00:00:00  11598.5470         130   
4        44471777  27902  2019-03-01 00:00:00  11643.2220         130   
...           ...    ...                  ...         ...         ...   
26229    43185353  27509  2022-02-01 00:00:00   4410.5530         125   
26230    43185354  27509  2022-01-01 00:00:00   4414.9590         125   
26231    43185355  27509  2021-12-01 00:00:00   4105.9120         125   
26232    43185356  27509  2021-11-01 00:00:00   4105.9120         125   
26233    43185357  27509  2021-10-01 00:00:00   4089.5212         125   

       max_in_version  
0           79575.234  
1           79575.234  
2           79575.234  
3           79575.234  
4           79575.234  
...               ...  
26229       50131.637  
26230       50131.637  
26231       50131.637  
26232       50131.637  
26233       50131.637  

[26234 rows x 6 columns]

**Q43.** Calculate the percentage contribution of each `data` value to the total sum of its version for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `data`, `version_id`, `percentage_of_total`.

in_timeseries_data
→ in_timeseries      (ts_id → version_id, geography_id)
→ in_resource        (geography_id → workspace_id)


In [68]:
result = ( in_timeseries_data.merge( in_timeseries, on="ts_id", how="inner")
           .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner" ))

version_total = result.groupby("version_id")["data"].transform("sum")

result["percentage_of_total"] = result["data"] / version_total * 100

result[["ts_data_id","ts_id","data","version_id","percentage_of_total"]]



ts_data_id  ts_id        data  version_id  percentage_of_total
0        44471796  27902  10549.2070         130             0.264083
1        44471774  27902  11513.3700         130             0.288220
2        44471775  27902  11556.1250         130             0.289290
3        44471776  27902  11598.5470         130             0.290352
4        44471777  27902  11643.2220         130             0.291470
...           ...    ...         ...         ...                  ...
26229    43185353  27509   4410.5530         125             0.003711
26230    43185354  27509   4414.9590         125             0.003714
26231    43185355  27509   4105.9120         125             0.003454
26232    43185356  27509   4105.9120         125             0.003454
26233    43185357  27509   4089.5212         125             0.003441

[26234 rows x 5 columns]

**Q44.** Find the first and last `data` values for each `ts_id` ordered by `dttime`, where `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `first_value`, `last_value`.

in_timeseries_data
→ in_timeseries      (ts_id → geography_id)
→ in_resource        (geography_id → workspace_id)


In [ ]:
result = (in_timeseries_data.merge(in_timeseries,on="ts_id",how="inner")
            .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner")
            .sort_values(["ts_id", "dttime"]))

result["first_value"] = result.groupby("ts_id")["data"].transform("first")

result["last_value"] =result.groupby("ts_id")["data"].transform("last")

result[["ts_data_id","ts_id","dttime","data","first_value","last_value"]]



ts_data_id  ts_id               dttime       data  first_value  \
268    43177787  27363  2018-01-01 00:00:00  2915.9478    2915.9478   
267    43177786  27363  2018-02-01 00:00:00  2846.3586    2915.9478   
266    43177785  27363  2018-03-01 00:00:00  3013.9375    2915.9478   
265    43177784  27363  2018-04-01 00:00:00  2057.4304    2915.9478   
264    43177783  27363  2018-05-01 00:00:00  2129.4080    2915.9478   
..          ...    ...                  ...        ...          ...   
150    44472893  27904  2025-01-01 00:00:00     0.0000     817.4324   
151    44472894  27904  2025-02-01 00:00:00     0.0000     817.4324   
152    44472895  27904  2025-03-01 00:00:00     0.0000     817.4324   
153    44472896  27904  2025-04-01 00:00:00     0.0000     817.4324   
154    44472897  27904  2025-05-01 00:00:00     0.0000     817.4324   

     last_value  
268    2055.375  
267    2055.375  
266    2055.375  
265    2055.375  
264    2055.375  
..          ...  
150       0.000  
151       0.000  
152       0.000  
153       0.000  
154       0.000  

[26234 rows x 6 columns]

**Q45.** Calculate the difference between each `data` value and the average `data` value within its version for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `data`, `version_id`, `avg_in_version`, `difference_from_avg`.

in_timeseries_data
→ in_timeseries      (ts_id → version_id, geography_id)
→ in_resource        (geography_id → workspace_id)


In [71]:
result = (in_timeseries_data.merge(in_timeseries,on="ts_id",how="inner")
            .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner")  )

result["avg_in_version"] =result.groupby("version_id")["data"].transform("mean")

result["difference_from_avg"] =result["data"] - result["avg_in_version"]

result[["ts_data_id","ts_id","data","version_id","avg_in_version","difference_from_avg"]]


ts_data_id  ts_id        data  version_id  avg_in_version  \
0        44471796  27902  10549.2070         130    17071.166382   
1        44471774  27902  11513.3700         130    17071.166382   
2        44471775  27902  11556.1250         130    17071.166382   
3        44471776  27902  11598.5470         130    17071.166382   
4        44471777  27902  11643.2220         130    17071.166382   
...           ...    ...         ...         ...             ...   
26229    43185353  27509   4410.5530         125     4571.663317   
26230    43185354  27509   4414.9590         125     4571.663317   
26231    43185355  27509   4105.9120         125     4571.663317   
26232    43185356  27509   4105.9120         125     4571.663317   
26233    43185357  27509   4089.5212         125     4571.663317   

       difference_from_avg  
0             -6521.959382  
1             -5557.796382  
2             -5515.041382  
3             -5472.619382  
4             -5427.944382  
...                    ...  
26229          -161.110317  
26230          -156.704317  
26231          -465.751317  
26232          -465.751317  
26233          -482.142117  

[26234 rows x 6 columns]

**Q46.** Rank materials by their total `data` sum across all timeseries in `workspace_id = 53`. Output columns: `material_id`, `material_name`, `total_data_sum`, `rank`.

in_timeseries_data
→ in_timeseries      (ts_id → material_id, geography_id)
→ in_resource        (geography_id → workspace_id)
→ in_material        (material_id → material_name)


In [73]:

df = in_timeseries_data.merge(in_timeseries,on="ts_id",how="inner") \
        .merge(in_resource[in_resource["workspace_id"] == 53],on="geography_id",how="inner")  \
            .merge(in_material,on="material_id",how="inner")

material_sum =df.groupby(["material_id", "material_name"], as_index=False)["data"].sum().rename(columns={"data": "total_data_sum"})

material_sum["rank"] = material_sum["total_data_sum"].rank(method="dense", ascending=False)

material_sum.sort_values("rank")


material_id  material_name  total_data_sum  rank
2        83500        HSD Reg    5.789561e+07   1.0
0        83498         MS Reg    4.464723e+07   2.0
3        83501       HSD Prem    8.706305e+06   3.0
1        83499        MS Prem    6.524664e+06   4.0
5        83506        Regular    3.441100e+06   5.0
4        83502  Lube20w40 XYZ    1.089444e+06   6.0
6        83507        Premium    5.168628e+05   7.0
7        83508            XYZ    3.669039e+04   8.0

**Q47.** Display all timeseries data records where the `data` value is greater than the average `data` value across all records in `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`.

in_timeseries_data
→ in_timeseries      (ts_id → version_id, geography_id)
→ in_resource        (geography_id → workspace_id)


In [74]:
df =in_timeseries_data.merge( in_timeseries, on="ts_id", how="inner")  \
        .merge( in_resource[in_resource["workspace_id"] == 53], on="geography_id", how="inner")

avg_data = df["data"].mean()

result = df[df["data"] > avg_data][["ts_data_id","ts_id","dttime","data","version_id"]]

result


ts_data_id  ts_id               dttime       data  version_id
0        44471796  27902  2020-10-01 00:00:00  10549.207         130
1        44471774  27902  2018-12-01 00:00:00  11513.370         130
2        44471775  27902  2019-01-01 00:00:00  11556.125         130
3        44471776  27902  2019-02-01 00:00:00  11598.547         130
4        44471777  27902  2019-03-01 00:00:00  11643.222         130
...           ...    ...                  ...        ...         ...
26082    43193227  27660  2021-03-01 00:00:00  14212.298         125
26083    43193228  27660  2021-02-01 00:00:00  13846.691         125
26084    43193229  27660  2021-01-01 00:00:00  14107.458         125
26085    43193230  27660  2020-12-01 00:00:00  10757.089         125
26086    43193231  27660  2020-11-01 00:00:00  10592.488         125

[7260 rows x 5 columns]

**Q48.** Find the material with the maximum number of timeseries records in `workspace_id = 53`. Output columns: `material_id`, `material_name`, `timeseries_count`.

in_timeseries_data
→ in_timeseries      (ts_id → material_id, geography_id)
→ in_resource        (geography_id → workspace_id)
→ in_material        (material_id → material_name)


In [79]:
df = (in_timeseries_data.merge(in_timeseries, on="ts_id", how="inner")
        .merge( in_resource[in_resource["workspace_id"] == 53], on="geography_id", how="inner")
            .merge(in_material,on="material_id",how="inner") )

material_counts =df.groupby(["material_id", "material_name"], as_index=False).size().rename(columns={"size": "timeseries_count"})

material_counts.sort_values("timeseries_count", ascending=False).head(1)


material_id material_name  timeseries_count
0        83498        MS Reg              5200

# ------------------------------------------------------------------------------