# PySpark DataFrame Assignment


## Files Required
Place these CSV files alongside the notebook (or update paths in the load cell):
- sy_account_20251225_155056.csv
- ab_user_20251225_155056.csv
- sy_app_module_20251225_155056.csv
- sy_application_20251225_155056.csv
- in_model_20251225_155056.csv
- in_workspace_20251225_155056.csv
- in_timeseries_version_20251225_155057.csv
- in_material_20251225_155057.csv
- in_resource_20251225_155057.csv
- in_time_dimension_20251225_155057.csv
- in_timeseries_20251225_155057.csv
- in_timeseries_data_20251225_155101.csv

> **Note:** Use only PySpark DataFrame operations (e.g., `select`, `filter`, `join`, `groupBy`, `agg`, `orderBy`, window functions). Do not include solutions below the questions.


In [201]:
# Necessary libraries for PySpark
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql import Window
spark = SparkSession.builder.appName('pyspark_assignment').getOrCreate()
spark.conf.set('spark.sql.shuffle.partitions', '8')  # smaller partitions for local runs


In [202]:
# Load CSVs into PySpark DataFrames (adjust paths if needed)

ab_user_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\ab_user_20251225_155056.csv",header=True)
in_material_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_material_20251225_155057.csv",header=True)
in_model_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_model_20251225_155056.csv",header=True)
in_resource_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_resource_20251225_155057.csv",header=True)
in_time_dimension_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_time_dimension_20251225_155057.csv",header=True)
in_timeseries_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_timeseries_20251225_155057.csv",header=True)
in_timeseries_data_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_timeseries_data_20251225_155101.csv",header=True)
in_timeseries_version_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_timeseries_version_20251225_155057.csv",header=True)
in_workspace_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_workspace_20251225_155056.csv",header=True)
sy_account_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\sy_account_20251225_155056.csv",header=True)
sy_app_module_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\sy_app_module_20251225_155056.csv",header=True)
sy_application_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\sy_application_20251225_155056.csv",header=True)

**Q1.** Retrieve all columns from the `sy_account` table.

In [203]:
sy_account_df.columns

['id', 'name']

**Q2.** Find all users from the `ab_user` table where `account_id = 3`.

In [204]:
ab_user_df.filter(F.col("account_id")==3).show()

+---+--------+----------+
| id|username|account_id|
+---+--------+----------+
|  7|pratik.m|         3|
+---+--------+----------+



**Q3.** Display all application modules from `sy_app_module` ordered by `app_name` in ascending order.

In [205]:
sy_app_module_df.orderBy(F.col("app_name").asc()).show()

+------+--------------+--------+--------------------+
|app_id|application_id|app_code|            app_name|
+------+--------------+--------+--------------------+
|    14|             3|    xsfc|Radar-Demand Plan...|
|     6|             2|    xpnp|        Trinity-S&OP|
|    19|             5|    xbds| XBridge-Integration|
+------+--------------+--------+--------------------+



**Q4.** Fetch the first 10 records from the `in_timeseries_data` table.

In [206]:
in_timeseries_data_df.show(10)

+----------+-----+-------------------+---------+----------+
|ts_data_id|ts_id|             dttime|     data|version_id|
+----------+-----+-------------------+---------+----------+
|  44471796|27902|2020-10-01 00:00:00|10549.207|       130|
|  44471774|27902|2018-12-01 00:00:00| 11513.37|       130|
|  44471775|27902|2019-01-01 00:00:00|11556.125|       130|
|  44471776|27902|2019-02-01 00:00:00|11598.547|       130|
|  44471777|27902|2019-03-01 00:00:00|11643.222|       130|
|  44471778|27902|2019-04-01 00:00:00| 11687.96|       130|
|  44471779|27902|2019-05-01 00:00:00|11732.147|       130|
|  44471780|27902|2019-06-01 00:00:00|11775.567|       130|
|  44471781|27902|2019-07-01 00:00:00|11820.099|       130|
|  44471782|27902|2019-08-01 00:00:00|11863.516|       130|
+----------+-----+-------------------+---------+----------+
only showing top 10 rows



**Q5.** Count the total number of materials in `in_material` for `workspace_id = 53`.

In [207]:
in_material_df.filter(F.col("workspace_id")==53).count()

19

**Q6.** Display all users from `ab_user` ordered by `username` in ascending order.

In [208]:
ab_user_df.orderBy(F.col("username").asc()).show()

+---+-----------+----------+
| id|   username|account_id|
+---+-----------+----------+
|  1|      admin|         1|
|  5| customer_1|         1|
|  3|hetal.patel|         1|
|  7|   pratik.m|         3|
|  4|       ravi|         1|
+---+-----------+----------+



**Q7.** Find all timeseries from `in_timeseries` where `time_level_id = 5` and `material_id = 83498`.

In [209]:
in_timeseries_df.filter((F.col("time_level_id")==5) & (F.col("material_id")==83498)).show()

+-----+-----------+------------+-------------+
|ts_id|material_id|geography_id|time_level_id|
+-----+-----------+------------+-------------+
|27803|      83498|       30201|            5|
|27808|      83498|       30202|            5|
|27813|      83498|       30203|            5|
|27818|      83498|       30204|            5|
|27823|      83498|       30205|            5|
|27828|      83498|       30206|            5|
|27363|      83498|       30113|            5|
|27368|      83498|       30114|            5|
|27373|      83498|       30115|            5|
|27378|      83498|       30116|            5|
|27383|      83498|       30117|            5|
|27388|      83498|       30118|            5|
|27393|      83498|       30119|            5|
|27398|      83498|       30120|            5|
|27403|      83498|       30121|            5|
|27408|      83498|       30122|            5|
|27413|      83498|       30123|            5|
|27418|      83498|       30124|            5|
|27423|      

**Q8.** Retrieve all versions from `in_timeseries_version` where `version_id` is 125, 126, or 130.

In [210]:
in_timeseries_data_df.filter(F.col("version_id").isin([125,126,130])).show()

+----------+-----+-------------------+---------+----------+
|ts_data_id|ts_id|             dttime|     data|version_id|
+----------+-----+-------------------+---------+----------+
|  44471796|27902|2020-10-01 00:00:00|10549.207|       130|
|  44471774|27902|2018-12-01 00:00:00| 11513.37|       130|
|  44471775|27902|2019-01-01 00:00:00|11556.125|       130|
|  44471776|27902|2019-02-01 00:00:00|11598.547|       130|
|  44471777|27902|2019-03-01 00:00:00|11643.222|       130|
|  44471778|27902|2019-04-01 00:00:00| 11687.96|       130|
|  44471779|27902|2019-05-01 00:00:00|11732.147|       130|
|  44471780|27902|2019-06-01 00:00:00|11775.567|       130|
|  44471781|27902|2019-07-01 00:00:00|11820.099|       130|
|  44471782|27902|2019-08-01 00:00:00|11863.516|       130|
|  44471783|27902|2019-09-01 00:00:00|11907.183|       130|
|  44471784|27902|2019-10-01 00:00:00|11949.934|       130|
|  44471785|27902|2019-11-01 00:00:00|11994.433|       130|
|  44471786|27902|2019-12-01 00:00:00|12

**Q9.** Retrieve the first 5 materials from `in_material` where `workspace_id = 53`, ordered by `material_name`.

In [211]:
in_material_df.orderBy(F.col("material_name")).filter(F.col("workspace_id")==53).show(5)

+-----------+-------------+------------+
|material_id|material_name|workspace_id|
+-----------+-------------+------------+
|      83516|          All|          53|
|      83505|    Auto Lube|          53|
|      83504|       Diesel|          53|
|      83509|         Fuel|          53|
|      83503|     Gasoline|          53|
+-----------+-------------+------------+
only showing top 5 rows



**Q10.** Count the total number of users in the `ab_user` table.

In [212]:
ab_user_df.count()

5

**Q11.** Calculate the sum of all `data` values from `in_timeseries_data` where `version_id = 125`.

In [213]:
in_timeseries_data_df.filter(F.col("version_id")==125).count()

26000

**Q12.** Find the average value of `data` from `in_timeseries_data` where `version_id = 125`.

In [214]:
in_timeseries_data_df.filter(F.col("version_id") == 125) \
                    .select(F.avg("data").alias("avg_data")).show()

+------------------+
|          avg_data|
+------------------+
|4571.6633166697975|
+------------------+



**Q13.** Find the maximum and minimum `data` values from `in_timeseries_data` where `version_id = 130`.

In [215]:
in_timeseries_data_df.filter(F.col("version_id") == 130) \
                    .select(F.max("data").alias("max_data"),F.min("data").alias("min_data")).show()

+--------+--------+
|max_data|min_data|
+--------+--------+
|959.9358|     0.0|
+--------+--------+



**Q14.** Count the number of timeseries records grouped by `material_id` from `in_timeseries`.

In [216]:
in_timeseries_df.groupBy("material_id").count().show()

+-----------+-----+
|material_id|count|
+-----------+-----+
|      83500|  100|
|      83502|  100|
|      83499|  100|
|      83504|  100|
|      83505|  100|
|      83498|  100|
|      83506|    1|
|      83501|  100|
|      83503|  100|
|      83507|    1|
|      83508|    1|
+-----------+-----+



**Q15.** Count the number of users grouped by `account_id` where `account_id` is not null.

In [217]:
ab_user_df.groupBy(F.col("account_id")==None).count().show()

+-------------------+-----+
|(account_id = NULL)|count|
+-------------------+-----+
|               NULL|    5|
+-------------------+-----+



**Q16.** Display `version_id`, total record count, and average `data` value grouped by `version_id` from `in_timeseries_data`.

In [218]:
in_timeseries_data_df.groupBy("version_id") \
        .agg(F.count("*").alias("rec_count"),F.avg("data").alias("avg_data")).show()
        

+----------+---------+------------------+
|version_id|rec_count|          avg_data|
+----------+---------+------------------+
|       125|    26000|4571.6633166697975|
|       130|      234|17071.166381623927|
+----------+---------+------------------+



**Q17.** Find all `material_id` values that have more than 3 timeseries records.

In [219]:
in_material_df.filter(F.col("material_id")>=3).show()

+-----------+-------------+------------+
|material_id|material_name|workspace_id|
+-----------+-------------+------------+
|      83515|      LB20W40|          53|
|      83498|       MS Reg|          53|
|      83499|      MS Prem|          53|
|      83500|      HSD Reg|          53|
|      83501|     HSD Prem|          53|
|      83502|Lube20w40 XYZ|          53|
|      83503|     Gasoline|          53|
|      83504|       Diesel|          53|
|      83505|    Auto Lube|          53|
|      83506|      Regular|          53|
|      83507|      Premium|          53|
|      83508|          XYZ|          53|
|      83509|         Fuel|          53|
|      83510|   Lubricants|          53|
|      83511|         MS92|          53|
|      83512|         MS95|          53|
|      83513|         HSDR|          53|
|      83514|        HSDRP|          53|
|      83516|          All|          53|
+-----------+-------------+------------+



**Q18.** Count the number of timeseries data records grouped by both `version_id` and `ts_id` and show only those with `count > 1`.

In [220]:
in_timeseries_data_df.groupBy("version_id","ts_id").agg(F.count("*").alias("count")).filter(F.col("count")>1).show()

+----------+-----+-----+
|version_id|ts_id|count|
+----------+-----+-----+
|       125|27373|   52|
|       125|27375|   52|
|       125|27389|   52|
|       125|27392|   52|
|       125|27419|   52|
|       125|27430|   52|
|       125|27436|   52|
|       125|27438|   52|
|       125|27458|   52|
|       125|27470|   52|
|       125|27474|   52|
|       125|27487|   52|
|       125|27489|   52|
|       125|27490|   52|
|       125|27491|   52|
|       125|27498|   52|
|       125|27507|   52|
|       125|27519|   52|
|       125|27532|   52|
|       125|27534|   52|
+----------+-----+-----+
only showing top 20 rows



**Q19.** Display `username` along with account name. Output columns: `id`, `username`, `account_id`, `name`.

In [221]:
ab_user_df.join(sy_account_df,on="id",how="inner").show()

+---+-----------+----------+-------------------+
| id|   username|account_id|               name|
+---+-----------+----------+-------------------+
|  1|      admin|         1|       ESPL_Account|
|  3|hetal.patel|         1|              Enpro|
|  4|       ravi|         1|         Indian Oil|
|  5| customer_1|         1|Standard Automotive|
|  7|   pratik.m|         3|           ESPL_UAT|
+---+-----------+----------+-------------------+



**Q20.** Show all application names and their corresponding application module details. Output columns: `app_id`, `app_code`, `app_name`, `application_id`, `application_name`.

In [222]:
sy_application_df.join(sy_app_module_df,on="application_id",how="inner") \
    .select("app_id","app_code","app_name","application_id","application_name").show()

+------+--------+--------------------+--------------+----------------+
|app_id|app_code|            app_name|application_id|application_name|
+------+--------+--------------------+--------------+----------------+
|    19|    xbds| XBridge-Integration|             5|         XBridge|
|    14|    xsfc|Radar-Demand Plan...|             3|          XSight|
|     6|    xpnp|        Trinity-S&OP|             2|           XPlan|
+------+--------+--------------------+--------------+----------------+



**Q21.** Retrieve model names along with their associated application names. Output columns: `model_id`, `model_name`, `application_id`, `application_name`.

In [223]:
in_model_df.join(sy_application_df,on="application_id",how="inner") \
    .select("model_id","model_name","application_id","application_name").show()

+--------+-----------+--------------+----------------+
|model_id| model_name|application_id|application_name|
+--------+-----------+--------------+----------------+
|      29|Oil and Gas|             3|          XSight|
+--------+-----------+--------------+----------------+



**Q22.** Display workspace names with their corresponding model names. Output columns: `workspace_id`, `workspace_name`, `model_id`, `model_name`.

In [224]:
in_workspace_df.join(in_model_df,on="model_id",how="inner") \
    .select("workspace_id","workspace_name","model_id","model_name").show()

+------------+--------------+--------+-----------+
|workspace_id|workspace_name|model_id| model_name|
+------------+--------------+--------+-----------+
|          53|        Nayara|      29|Oil and Gas|
+------------+--------------+--------+-----------+



**Q23.** Show all version names along with their workspace names where `workspace_id = 53`. Output columns: `version_id`, `version_name`, `workspace_id`, `workspace_name`.

In [225]:
in_timeseries_version_df.join(in_workspace_df,how="cross").filter(F.col("workspace_id")==53) \
    .select("version_id","version_name","workspace_id","workspace_name").show()

+----------+------------------+------------+--------------+
|version_id|      version_name|workspace_id|workspace_name|
+----------+------------------+------------+--------------+
|       125|               Raw|          53|        Nayara|
|       126|Manually Corrected|          53|        Nayara|
|       130|       Forecast-MA|          53|        Nayara|
|       135|  Forecast-Bestfit|          53|        Nayara|
+----------+------------------+------------+--------------+



**Q24.** Display material names with their workspace names. Output columns: `material_id`, `material_name`, `workspace_id`, `workspace_name`.

In [226]:
in_material_df.join(in_workspace_df,on="workspace_id",how="inner") \
    .select("material_id","material_name","workspace_id","workspace_name").show()

+-----------+-------------+------------+--------------+
|material_id|material_name|workspace_id|workspace_name|
+-----------+-------------+------------+--------------+
|      83515|      LB20W40|          53|        Nayara|
|      83498|       MS Reg|          53|        Nayara|
|      83499|      MS Prem|          53|        Nayara|
|      83500|      HSD Reg|          53|        Nayara|
|      83501|     HSD Prem|          53|        Nayara|
|      83502|Lube20w40 XYZ|          53|        Nayara|
|      83503|     Gasoline|          53|        Nayara|
|      83504|       Diesel|          53|        Nayara|
|      83505|    Auto Lube|          53|        Nayara|
|      83506|      Regular|          53|        Nayara|
|      83507|      Premium|          53|        Nayara|
|      83508|          XYZ|          53|        Nayara|
|      83509|         Fuel|          53|        Nayara|
|      83510|   Lubricants|          53|        Nayara|
|      83511|         MS92|          53|        

**Q25.** Show resource (geography) names along with their workspace names where `workspace_id = 53`. Output columns: `resource_id`, `resource_name`, `workspace_id`, `workspace_name`.

In [227]:
in_resource_df.join(in_workspace_df,on="workspace_id",how="inner").filter(F.col("workspace_id")==53) \
    .select("geography_id","resource_name","workspace_id","workspace_name").show()

+------------+--------------------+------------+--------------+
|geography_id|       resource_name|workspace_id|workspace_name|
+------------+--------------------+------------+--------------+
|       30113|  Elhaam Corporation|          53|        Nayara|
|       30114| Yashkalgi Petroleum|          53|        Nayara|
|       30115|  Sukhmani Petroleum|          53|        Nayara|
|       30116|Vrajpari Corporation|          53|        Nayara|
|       30117|Sai Shakti Petroleum|          53|        Nayara|
|       30118|           BMF Fuels|          53|        Nayara|
|       30119|       R K Petroleum|          53|        Nayara|
|       30120|    Aastha Petroleum|          53|        Nayara|
|       30121|        JP Petroleum|          53|        Nayara|
|       30122|   UmiyaJi Petroleum|          53|        Nayara|
|       30123|Nilkanth Petroleu...|          53|        Nayara|
|       30124|    Rusabh Petroleum|          53|        Nayara|
|       30125|Nilkanth Petroleu...|     

**Q26.** Display time dimension names with their associated workspace names. Output columns: `time_dimension_id`, `time_dimension_name`, `workspace_id`, `workspace_name`.

In [228]:
in_time_dimension_df.join(in_workspace_df,on="workspace_id",how="inner") \
    .select("time_level_id","time_dimension_name","workspace_id","workspace_name").show()

+-------------+-------------------+------------+--------------+
|time_level_id|time_dimension_name|workspace_id|workspace_name|
+-------------+-------------------+------------+--------------+
|           64|            Quarter|          53|        Nayara|
|           65|               Year|          53|        Nayara|
|           63|              Month|          53|        Nayara|
+-------------+-------------------+------------+--------------+



**Q27.** Show timeseries IDs along with their corresponding material names where `workspace_id = 53`. Output columns: `ts_id`, `material_id`, `material_name`, `workspace_id`.

In [229]:
in_timeseries_df.join(in_material_df,on="material_id",how="inner").filter(F.col("workspace_id")==53) \
    .select("ts_id","material_id","material_name","workspace_id").show()

+-----+-----------+-------------+------------+
|ts_id|material_id|material_name|workspace_id|
+-----+-----------+-------------+------------+
|27803|      83498|       MS Reg|          53|
|27804|      83499|      MS Prem|          53|
|27805|      83500|      HSD Reg|          53|
|27806|      83501|     HSD Prem|          53|
|27807|      83502|Lube20w40 XYZ|          53|
|27808|      83498|       MS Reg|          53|
|27809|      83499|      MS Prem|          53|
|27810|      83500|      HSD Reg|          53|
|27811|      83501|     HSD Prem|          53|
|27812|      83502|Lube20w40 XYZ|          53|
|27813|      83498|       MS Reg|          53|
|27814|      83499|      MS Prem|          53|
|27815|      83500|      HSD Reg|          53|
|27816|      83501|     HSD Prem|          53|
|27817|      83502|Lube20w40 XYZ|          53|
|27818|      83498|       MS Reg|          53|
|27819|      83499|      MS Prem|          53|
|27820|      83500|      HSD Reg|          53|
|27821|      

**Q28.** Display timeseries data along with their version names where `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `version_name`.

in_timeseries_data
→ in_timeseries        (ts_id)
→ in_resource          (geography_id → workspace_id)
→ in_timeseries_version (version_id)


In [230]:
in_timeseries_data_df.join(in_timeseries_df,on="ts_id",how="inner") \
    .join(in_resource_df,on="geography_id",how="inner") \
    .join(in_timeseries_version_df,on="version_id",how="inner") \
    .filter(F.col("workspace_id")==53) \
    .select("ts_data_id","ts_id","dttime","data","version_id","version_name").show()

+----------+-----+-------------------+---------+----------+------------+
|ts_data_id|ts_id|             dttime|     data|version_id|version_name|
+----------+-----+-------------------+---------+----------+------------+
|  44471796|27902|2020-10-01 00:00:00|10549.207|       130| Forecast-MA|
|  44471774|27902|2018-12-01 00:00:00| 11513.37|       130| Forecast-MA|
|  44471775|27902|2019-01-01 00:00:00|11556.125|       130| Forecast-MA|
|  44471776|27902|2019-02-01 00:00:00|11598.547|       130| Forecast-MA|
|  44471777|27902|2019-03-01 00:00:00|11643.222|       130| Forecast-MA|
|  44471778|27902|2019-04-01 00:00:00| 11687.96|       130| Forecast-MA|
|  44471779|27902|2019-05-01 00:00:00|11732.147|       130| Forecast-MA|
|  44471780|27902|2019-06-01 00:00:00|11775.567|       130| Forecast-MA|
|  44471781|27902|2019-07-01 00:00:00|11820.099|       130| Forecast-MA|
|  44471782|27902|2019-08-01 00:00:00|11863.516|       130| Forecast-MA|
|  44471783|27902|2019-09-01 00:00:00|11907.183|   

**Q29.** Show all users and their account names where `account_id > 1`. Output columns: `id`, `username`, `account_id`, `name`.

In [231]:
ab_user_df.join(sy_account_df,on="id",how="inner").filter(F.col("account_id")>1) \
    .select("id","username","account_id","name").show()

+---+--------+----------+--------+
| id|username|account_id|    name|
+---+--------+----------+--------+
|  7|pratik.m|         3|ESPL_UAT|
+---+--------+----------+--------+



**Q30.** Display application module names along with their application descriptions. Output columns: `app_id`, `app_name`, `application_id`, `application_name`, `application_description`.

In [232]:
in_model_df.join(sy_application_df,on="application_id",how="inner") \
    .join(sy_app_module_df.alias("am"),on="application_id",how="inner") \
    .select("am.app_id","app_name","application_name","application_description").show()

+------+--------------------+----------------+-----------------------+
|app_id|            app_name|application_name|application_description|
+------+--------------------+----------------+-----------------------+
|    14|Radar-Demand Plan...|          XSight|   XSoght: Predictiv...|
+------+--------------------+----------------+-----------------------+



**Q31.** Show model names and their descriptions along with the application module name. Output columns: `model_id`, `model_name`, `model_description`, `app_id`, `app_name`.

In [233]:
in_model_df.join(sy_app_module_df.alias("am"),on="application_id",how="inner") \
    .select("model_id","model_name","model_description","am.app_id","app_name").show()

+--------+-----------+------------------+------+--------------------+
|model_id| model_name| model_description|app_id|            app_name|
+--------+-----------+------------------+------+--------------------+
|      29|Oil and Gas|Oil and Gas Sector|    14|Radar-Demand Plan...|
+--------+-----------+------------------+------+--------------------+



**Q32.** Show workspace name, model name, and application name for `workspace_id = 53`. Output columns: `workspace_id`, `workspace_name`, `model_id`, `model_name`, `application_id`, `application_name`.

In [234]:
in_workspace_df.join(in_model_df,on="model_id",how="inner") \
        .join(sy_application_df,on="application_id",how="inner").filter(F.col("workspace_id")==53) \
            .select("workspace_id","workspace_name","model_id","model_name","application_id","application_name").show()

+------------+--------------+--------+-----------+--------------+----------------+
|workspace_id|workspace_name|model_id| model_name|application_id|application_name|
+------------+--------------+--------+-----------+--------------+----------------+
|          53|        Nayara|      29|Oil and Gas|             3|          XSight|
+------------+--------------+--------+-----------+--------------+----------------+



**Q33.** Display timeseries ID, material name, geography name, and time dimension name for `workspace_id = 53`. Output columns: `ts_id`, `material_id`, `material_name`, `resource_id`, `resource_name`, `time_dimension_id`, `time_dimension_name`.

In [235]:
in_timeseries_df.join(in_material_df,on="material_id",how="inner") \
    .join(in_resource_df.alias("r"),on="geography_id",how="inner") \
        .join(in_time_dimension_df.alias("td"),on="workspace_id",how="inner").filter(F.col("r.workspace_id")==53) \
            .select("ts_id","material_id","material_name","r.geography_id","resource_name","td.time_level_id","time_dimension_name").show()

+-----+-----------+-------------+------------+-------------+-------------+-------------------+
|ts_id|material_id|material_name|geography_id|resource_name|time_level_id|time_dimension_name|
+-----+-----------+-------------+------------+-------------+-------------+-------------------+
|27803|      83498|       MS Reg|       30201|    S S Fuels|           63|              Month|
|27803|      83498|       MS Reg|       30201|    S S Fuels|           65|               Year|
|27803|      83498|       MS Reg|       30201|    S S Fuels|           64|            Quarter|
|27804|      83499|      MS Prem|       30201|    S S Fuels|           63|              Month|
|27804|      83499|      MS Prem|       30201|    S S Fuels|           65|               Year|
|27804|      83499|      MS Prem|       30201|    S S Fuels|           64|            Quarter|
|27805|      83500|      HSD Reg|       30201|    S S Fuels|           63|              Month|
|27805|      83500|      HSD Reg|       30201|    

**Q34.** Display timeseries data value, material name, geography name, and version name where `workspace_id = 53` and `version_id = 125`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `material_id`, `material_name`, `resource_id`, `resource_name`, `version_id`, `version_name`.

In [236]:
in_timeseries_data_df.alias("td").join(in_timeseries_version_df.alias("tv"),on="version_id",how="inner") \
    .join(in_timeseries_df,on="ts_id",how="inner") \
        .join(in_material_df.alias("m"),on="material_id",how="inner") \
            .join(in_resource_df.alias("r"),on="workspace_id",how="inner").filter(F.col("workspace_id")==53) \
    .select("td.ts_data_id","td.ts_id","td.dttime","td.data","m.material_id","m.material_name","r.geography_id","r.resource_name","td.version_id","tv.version_name") \
        .show()

+----------+-----+-------------------+---------+-----------+-------------+------------+--------------+----------+------------+
|ts_data_id|ts_id|             dttime|     data|material_id|material_name|geography_id| resource_name|version_id|version_name|
+----------+-----+-------------------+---------+-----------+-------------+------------+--------------+----------+------------+
|  44471796|27902|2020-10-01 00:00:00|10549.207|      83507|      Premium|       30241|       Bhiwadi|       130| Forecast-MA|
|  44471796|27902|2020-10-01 00:00:00|10549.207|      83507|      Premium|       30240|          Kota|       130| Forecast-MA|
|  44471796|27902|2020-10-01 00:00:00|10549.207|      83507|      Premium|       30239|       Jodhpur|       130| Forecast-MA|
|  44471796|27902|2020-10-01 00:00:00|10549.207|      83507|      Premium|       30238|        Jaipur|       130| Forecast-MA|
|  44471796|27902|2020-10-01 00:00:00|10549.207|      83507|      Premium|       30237|         Akola|       13

**Q35.** Show the latest 10 timeseries records (by datetime descending) for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `material_name`, `resource_name`, `time_dimension_name`, `version_name`, `workspace_name`.

In [237]:
in_timeseries_data_df.join(in_timeseries_df, on="ts_id", how="inner") \
    .join(in_material_df, on="material_id", how="inner")  \
    .join(in_resource_df[in_resource_df["workspace_id"] == 53],on="geography_id", how="inner") \
    .join(in_time_dimension_df, on="time_level_id", how="inner") \
    .join(in_timeseries_version_df, on="version_id", how="inner") \
    .join(in_workspace_df, on="workspace_id", how="inner") \
        .select("ts_data_id","ts_id","dttime","data","material_name","resource_name","time_dimension_name","version_name","workspace_name") \
            .show()

+----------+-----+------+----+-------------+-------------+-------------------+------------+--------------+
|ts_data_id|ts_id|dttime|data|material_name|resource_name|time_dimension_name|version_name|workspace_name|
+----------+-----+------+----+-------------+-------------+-------------------+------------+--------------+
+----------+-----+------+----+-------------+-------------+-------------------+------------+--------------+



**Q36.** Assign a row number to each timeseries data record within `workspace_id = 53`, ordered by `dttime`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `row_num`.

In [238]:
from pyspark.sql.window import Window

window_36= Window.orderBy("dttime")

in_timeseries_data_df.join(in_timeseries_version_df,on="version_id",how="inner") \
        .select("ts_data_id", "ts_id", "dttime", "data", "version_id") \
            .withColumn("row_num", F.row_number().over(window_36)).show()


+----------+-----+-------------------+----------+----------+-------+
|ts_data_id|ts_id|             dttime|      data|version_id|row_num|
+----------+-----+-------------------+----------+----------+-------+
|  43179600|27398|2018-01-01 00:00:00|  71.55379|       125|      1|
|  43180659|27419|2018-01-01 00:00:00|   36.3825|       125|      2|
|  43179704|27400|2018-01-01 00:00:00|  99.41498|       125|      3|
|  43177995|27367|2018-01-01 00:00:00| 58.944374|       125|      4|
|  43179756|27401|2018-01-01 00:00:00| 11.840634|       125|      5|
|  43178157|27371|2018-01-01 00:00:00|  2901.168|       125|      6|
|  43179807|27402|2018-01-01 00:00:00| 1.4639626|       125|      7|
|  43178320|27374|2018-01-01 00:00:00| 2324.7139|       125|      8|
|  43179867|27403|2018-01-01 00:00:00|10414.8545|       125|      9|
|  43178535|27378|2018-01-01 00:00:00| 25692.166|       125|     10|
|  43179918|27404|2018-01-01 00:00:00| 1280.0442|       125|     11|
|  43178690|27381|2018-01-01 00:00

**Q37.** Rank timeseries data values within each `version_id` for `workspace_id = 53`, ordered by `data` value descending. Output columns: `ts_data_id`, `ts_id`, `data`, `version_id`, `rank`.

In [239]:
window_37=Window.orderBy(F.col("data").desc())

in_timeseries_data_df.withColumn("rank",F.rank().over(window_37)) \
    .select("ts_data_id","ts_id","data","version_id","rank").show()

+----------+-----+--------+----------+----+
|ts_data_id|ts_id|    data|version_id|rank|
+----------+-----+--------+----------+----+
|  43194636|27688|9999.566|       125|   1|
|  43198580|27763|9998.707|       125|   2|
|  43194157|27678|9997.176|       125|   3|
|  43193960|27675|9996.405|       125|   4|
|  43182558|27455|9994.589|       125|   5|
|  43187743|27555|999.3399|       125|   6|
|  43192580|27648|9987.178|       125|   7|
|  43192446|27645|9986.819|       125|   8|
|  43202025|27830| 9986.42|       125|   9|
|  43194923|27693|9985.631|       125|  10|
|  43198816|27768|9983.248|       125|  11|
|  43189566|27590|9982.525|       125|  12|
|  43181745|27440|9981.848|       125|  13|
|  43196601|27725|9980.734|       125|  14|
|  43191404|27625|9978.993|       125|  15|
|  43197542|27743|9978.085|       125|  16|
|  43192576|27648| 9977.19|       125|  17|
|  43194008|27675|9976.452|       125|  18|
|  43187477|27550|9974.119|       125|  19|
|  43185948|27520|9973.939|     

**Q38.** Calculate the running total (cumulative sum) of `data` values for each `ts_id`, ordered by `dttime`, for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `running_total`.

In [240]:
window_38=Window.orderBy(F.col("dttime")).rowsBetween(Window.unboundedPreceding, Window.currentRow)

in_timeseries_data_df.withColumn("running_total",F.sum("data").over(window_38)).show()

+----------+-----+-------------------+---------+----------+------------------+
|ts_data_id|ts_id|             dttime|     data|version_id|     running_total|
+----------+-----+-------------------+---------+----------+------------------+
|  43177787|27363|2018-01-01 00:00:00|2915.9478|       125|         2915.9478|
|  43177995|27367|2018-01-01 00:00:00|58.944374|       125|       2974.892174|
|  43178002|27368|2018-01-01 00:00:00|18240.324|       125|      21215.216174|
|  43178157|27371|2018-01-01 00:00:00| 2901.168|       125|24116.384174000003|
|  43178268|27373|2018-01-01 00:00:00|19071.441|       125|      43187.825174|
|  43178320|27374|2018-01-01 00:00:00|2324.7139|       125|      45512.539074|
|  43178424|27376|2018-01-01 00:00:00|3224.8557|       125|      48737.394774|
|  43178535|27378|2018-01-01 00:00:00|25692.166|       125|      74429.560774|
|  43178586|27379|2018-01-01 00:00:00|3095.1455|       125|      77524.706274|
|  43178690|27381|2018-01-01 00:00:00| 4009.496|    

**Q39.** Find the previous and next `data` values for each timeseries record ordered by `dttime`, where `workspace_id = 53` and `version_id = 125`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `previous_value`, `next_value`.

In [241]:
window_39=Window.orderBy("dttime")

in_timeseries_data_df.filter(F.col("version_id")==125).withColumn("next_data",F.lead("data").over(window_39)) \
    .withColumn("prev_data",F.lag("data").over(window_39)).show()

+----------+-----+-------------------+---------+----------+---------+---------+
|ts_data_id|ts_id|             dttime|     data|version_id|next_data|prev_data|
+----------+-----+-------------------+---------+----------+---------+---------+
|  43177787|27363|2018-01-01 00:00:00|2915.9478|       125|58.944374|     NULL|
|  43177995|27367|2018-01-01 00:00:00|58.944374|       125|18240.324|2915.9478|
|  43178002|27368|2018-01-01 00:00:00|18240.324|       125| 2901.168|58.944374|
|  43178157|27371|2018-01-01 00:00:00| 2901.168|       125|19071.441|18240.324|
|  43178268|27373|2018-01-01 00:00:00|19071.441|       125|2324.7139| 2901.168|
|  43178320|27374|2018-01-01 00:00:00|2324.7139|       125|3224.8557|19071.441|
|  43178424|27376|2018-01-01 00:00:00|3224.8557|       125|25692.166|2324.7139|
|  43178535|27378|2018-01-01 00:00:00|25692.166|       125|3095.1455|3224.8557|
|  43178586|27379|2018-01-01 00:00:00|3095.1455|       125| 4009.496|25692.166|
|  43178690|27381|2018-01-01 00:00:00| 4

**Q40.** Calculate the moving average of `data` values over the last 3 records (including current) for each timeseries ordered by `dttime`, where `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `moving_avg_3`.

In [242]:

window_40 = Window.orderBy("dttime").rowsBetween(-2, 0)

in_timeseries_data_df.withColumn("avg_over_last_3", F.avg("data").over(window_40)).show()


+----------+-----+-------------------+---------+----------+------------------+
|ts_data_id|ts_id|             dttime|     data|version_id|   avg_over_last_3|
+----------+-----+-------------------+---------+----------+------------------+
|  43177787|27363|2018-01-01 00:00:00|2915.9478|       125|         2915.9478|
|  43177995|27367|2018-01-01 00:00:00|58.944374|       125|       1487.446087|
|  43178002|27368|2018-01-01 00:00:00|18240.324|       125| 7071.738724666667|
|  43178157|27371|2018-01-01 00:00:00| 2901.168|       125| 7066.812124666667|
|  43178268|27373|2018-01-01 00:00:00|19071.441|       125|13404.311000000002|
|  43178320|27374|2018-01-01 00:00:00|2324.7139|       125| 8099.107633333333|
|  43178424|27376|2018-01-01 00:00:00|3224.8557|       125| 8207.003533333333|
|  43178535|27378|2018-01-01 00:00:00|25692.166|       125|10413.911866666667|
|  43178586|27379|2018-01-01 00:00:00|3095.1455|       125|        10670.7224|
|  43178690|27381|2018-01-01 00:00:00| 4009.496|    

**Q41.** Assign a dense rank to materials based on the count of their timeseries records in `workspace_id = 53`. Output columns: `material_id`, `timeseries_count`, `dense_rank`.

In [243]:

material_count_df =in_timeseries_data_df.join(in_timeseries_df, on="ts_id", how="inner")\
                            .join(in_resource_df.filter(F.col("workspace_id") == 53),on="geography_id",how="inner")

material_df = material_count_df.groupBy("material_id").agg(F.count("*").alias("timeseries_count"))

window_41 = Window.orderBy(F.col("timeseries_count").desc())

material_df.withColumn("dense_rank", F.dense_rank().over(window_41)).show()


+-----------+----------------+----------+
|material_id|timeseries_count|dense_rank|
+-----------+----------------+----------+
|      83502|            5200|         1|
|      83500|            5200|         1|
|      83499|            5200|         1|
|      83498|            5200|         1|
|      83501|            5200|         1|
|      83506|              78|         2|
|      83507|              78|         2|
|      83508|              78|         2|
+-----------+----------------+----------+



**Q42.** Partition timeseries data by `version_id` and display the maximum `data` value within each version for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `max_in_version`.

In [244]:

in_timeseries_data_df.groupBy("version_id").agg(F.max("data").alias("max_in_version")).show()



+----------+--------------+
|version_id|max_in_version|
+----------+--------------+
|       125|      9999.566|
|       130|      959.9358|
+----------+--------------+



**Q43.** Calculate the percentage contribution of each `data` value to the total sum of its version for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `data`, `version_id`, `percentage_of_total`.

In [245]:
window_spec = Window.partitionBy("version_id")


in_timeseries_data_df.withColumn("version_total", F.sum("data").over(window_spec)) \
    .withColumn("percentage_of_total",(F.col("data") / F.col("version_total")) * 100) \
        .select("ts_data_id","ts_id","data","version_id","percentage_of_total").show()

+----------+-----+---------+----------+--------------------+
|ts_data_id|ts_id|     data|version_id| percentage_of_total|
+----------+-----+---------+----------+--------------------+
|  43177824|27364|381.43152|       125|3.208994639528634E-4|
|  43177754|27363|2041.8203|       125|0.001717789446866045|
|  43177755|27363| 1921.837|       125|0.001616847142325...|
|  43177756|27363|1991.6937|       125|0.001675617790287...|
|  43177757|27363|1933.8904|       125|0.001626987703332...|
|  43177758|27363|1984.3469|       125|0.001669436905755...|
|  43177759|27363|1891.3866|       125|0.001591229130900...|
|  43177760|27363|1829.2837|       125|0.001538981777771566|
|  43177761|27363|2682.4043|       125| 0.00225671465739081|
|  43177762|27363| 2533.259|       125|0.002131238276149...|
|  43177763|27363|2597.7861|       125|0.002185525115895508|
|  43177764|27363|2419.9697|       125|0.002035927653572447|
|  43177765|27363|2399.9453|       125|0.002019081066730...|
|  43177766|27363|2397.4

**Q44.** Find the first and last `data` values for each `ts_id` ordered by `dttime`, where `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `first_value`, `last_value`.

In [246]:

df=in_timeseries_data_df.join(in_timeseries_df, on="ts_id", how="inner") \
    .join(in_resource_df.filter(F.col("workspace_id") == 53),on="geography_id",how="inner")

window_spec =Window.partitionBy("ts_id").orderBy("dttime").rowsBetween(Window.unboundedPreceding, Window.unboundedFollowing)

df.withColumn("first_value", F.first("data").over(window_spec)).withColumn("last_value", F.last("data").over(window_spec)) \
    .select("ts_data_id","ts_id","dttime","data","first_value","last_value").show()


+----------+-----+-------------------+---------+-----------+----------+
|ts_data_id|ts_id|             dttime|     data|first_value|last_value|
+----------+-----+-------------------+---------+-----------+----------+
|  43177787|27363|2018-01-01 00:00:00|2915.9478|  2915.9478|  2055.375|
|  43177786|27363|2018-02-01 00:00:00|2846.3586|  2915.9478|  2055.375|
|  43177785|27363|2018-03-01 00:00:00|3013.9375|  2915.9478|  2055.375|
|  43177784|27363|2018-04-01 00:00:00|2057.4304|  2915.9478|  2055.375|
|  43177783|27363|2018-05-01 00:00:00| 2129.408|  2915.9478|  2055.375|
|  43177782|27363|2018-06-01 00:00:00| 2225.144|  2915.9478|  2055.375|
|  43177781|27363|2018-07-01 00:00:00|2172.9106|  2915.9478|  2055.375|
|  43177780|27363|2018-08-01 00:00:00|2237.8582|  2915.9478|  2055.375|
|  43177779|27363|2018-09-01 00:00:00|2159.3674|  2915.9478|  2055.375|
|  43177778|27363|2018-10-01 00:00:00|2294.1802|  2915.9478|  2055.375|
|  43177777|27363|2018-11-01 00:00:00|2296.5984|  2915.9478|  20

**Q45.** Calculate the difference between each `data` value and the average `data` value within its version for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `data`, `version_id`, `avg_in_version`, `difference_from_avg`.

In [247]:

df =in_timeseries_data_df.join(in_timeseries_df, on="ts_id", how="inner") \
    .join(in_resource_df.filter(F.col("workspace_id") == 53),on="geography_id",how="inner")

window_spec = Window.partitionBy("version_id")

df.withColumn("avg_in_version", F.avg("data").over(window_spec)) \
    .withColumn("difference_from_avg",F.col("data") - F.col("avg_in_version"))\
        .select("ts_data_id","ts_id","data","version_id","avg_in_version","difference_from_avg").show()


+----------+-----+---------+----------+------------------+-------------------+
|ts_data_id|ts_id|     data|version_id|    avg_in_version|difference_from_avg|
+----------+-----+---------+----------+------------------+-------------------+
|  43177824|27364|381.43152|       125|4571.6633166697975| -4190.231796669797|
|  43177754|27363|2041.8203|       125|4571.6633166697975| -2529.843016669797|
|  43177755|27363| 1921.837|       125|4571.6633166697975|-2649.8263166697975|
|  43177756|27363|1991.6937|       125|4571.6633166697975|-2579.9696166697977|
|  43177757|27363|1933.8904|       125|4571.6633166697975|-2637.7729166697973|
|  43177758|27363|1984.3469|       125|4571.6633166697975|-2587.3164166697975|
|  43177759|27363|1891.3866|       125|4571.6633166697975|-2680.2767166697977|
|  43177760|27363|1829.2837|       125|4571.6633166697975|-2742.3796166697975|
|  43177761|27363|2682.4043|       125|4571.6633166697975|-1889.2590166697973|
|  43177762|27363| 2533.259|       125|4571.66331666

**Q46.** Rank materials by their total `data` sum across all timeseries in `workspace_id = 53`. Output columns: `material_id`, `material_name`, `total_data_sum`, `rank`.

In [248]:

df = in_timeseries_data_df.join(in_timeseries_df, on="ts_id", how="inner")  \
    .join(in_resource_df.filter(F.col("workspace_id") == 53),on="geography_id",how="inner") \
    .join(in_material_df, on="material_id", how="inner")

material_sum_df =df.groupBy("material_id", "material_name").agg(F.sum("data").alias("total_data_sum"))

rank_window = Window.orderBy(F.col("total_data_sum").desc())

material_sum_df.withColumn("rank", F.dense_rank().over(rank_window)).orderBy("rank").show()



+-----------+-------------+-------------------+----+
|material_id|material_name|     total_data_sum|rank|
+-----------+-------------+-------------------+----+
|      83500|      HSD Reg|5.789560762242195E7|   1|
|      83498|       MS Reg|4.464722608354395E7|   2|
|      83501|     HSD Prem|  8706304.853283972|   3|
|      83499|      MS Prem|  6524663.734419964|   4|
|      83506|      Regular| 3441099.7019999996|   5|
|      83502|Lube20w40 XYZ| 1089443.9397443978|   6|
|      83507|      Premium|  516862.8430999999|   7|
|      83508|          XYZ|  36690.38820000001|   8|
+-----------+-------------+-------------------+----+



**Q47.** Display all timeseries data records where the `data` value is greater than the average `data` value across all records in `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`.

In [249]:

avg_data = in_timeseries_data_df.agg(F.avg("data").alias("avg_data")).collect()[0]["avg_data"]

df.filter(F.col("data") > avg_data).select("ts_data_id","ts_id","dttime","data","version_id").show()


+----------+-----+-------------------+---------+----------+
|ts_data_id|ts_id|             dttime|     data|version_id|
+----------+-----+-------------------+---------+----------+
|  44471796|27902|2020-10-01 00:00:00|10549.207|       130|
|  44471774|27902|2018-12-01 00:00:00| 11513.37|       130|
|  44471775|27902|2019-01-01 00:00:00|11556.125|       130|
|  44471776|27902|2019-02-01 00:00:00|11598.547|       130|
|  44471777|27902|2019-03-01 00:00:00|11643.222|       130|
|  44471778|27902|2019-04-01 00:00:00| 11687.96|       130|
|  44471779|27902|2019-05-01 00:00:00|11732.147|       130|
|  44471780|27902|2019-06-01 00:00:00|11775.567|       130|
|  44471781|27902|2019-07-01 00:00:00|11820.099|       130|
|  44471782|27902|2019-08-01 00:00:00|11863.516|       130|
|  44471783|27902|2019-09-01 00:00:00|11907.183|       130|
|  44471784|27902|2019-10-01 00:00:00|11949.934|       130|
|  44471785|27902|2019-11-01 00:00:00|11994.433|       130|
|  44471786|27902|2019-12-01 00:00:00|12

**Q48.** Find the material with the maximum number of timeseries records in `workspace_id = 53`. Output columns: `material_id`, `material_name`, `timeseries_count`.

In [250]:

df = in_timeseries_data_df.join(in_timeseries_df, on="ts_id", how="inner") \
    .join(in_resource_df.filter(F.col("workspace_id") == 53),on="geography_id",how="inner") \
    .join(in_material_df, on="material_id", how="inner")

material_counts_df = df.groupBy("material_id", "material_name").count().withColumnRenamed("count", "timeseries_count")

material_counts_df.orderBy( F.col("timeseries_count").desc()).limit(1).show()


+-----------+-------------+----------------+
|material_id|material_name|timeseries_count|
+-----------+-------------+----------------+
|      83502|Lube20w40 XYZ|            5200|
+-----------+-------------+----------------+



# -------------------------------------------------------------------------