# Spark SQL Assignment: Relational Queries

This notebook contains **questions only** (no solutions). Solve each using **Spark SQL** (i.e., `spark.sql(...)`).

## Files Required
Ensure the following CSV files are available (or update paths in the load cell):
- sy_account_20251225_155056.csv
- ab_user_20251225_155056.csv
- sy_app_module_20251225_155056.csv
- sy_application_20251225_155056.csv
- in_model_20251225_155056.csv
- in_workspace_20251225_155056.csv
- in_timeseries_version_20251225_155057.csv
- in_material_20251225_155057.csv
- in_resource_20251225_155057.csv
- in_time_dimension_20251225_155057.csv
- in_timeseries_20251225_155057.csv
- in_timeseries_data_20251225_155101.csv

> **Note:** The load cell registers **temporary views** with the same names so you can query them via `SELECT ... FROM view_name`.


In [1]:
# Initialize Spark for Spark SQL
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
spark = SparkSession.builder.appName('spark_sql_assignment').getOrCreate()
spark.conf.set('spark.sql.shuffle.partitions', '8')


In [2]:
# Load CSVs and create temp views for Spark SQL

ab_user_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\ab_user_20251225_155056.csv",header=True)
ab_user_df.createOrReplaceTempView("ab_user")

in_material_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_material_20251225_155057.csv",header=True)
in_material_df.createOrReplaceTempView("in_material")

in_model_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_model_20251225_155056.csv",header=True)
in_model_df.createOrReplaceTempView("in_model")

in_resource_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_resource_20251225_155057.csv",header=True)
in_resource_df.createOrReplaceTempView("in_resource")

in_time_dimension_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_time_dimension_20251225_155057.csv",header=True)
in_time_dimension_df.createOrReplaceTempView("in_time_dimension")

in_timeseries_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_timeseries_20251225_155057.csv",header=True)
in_timeseries_df.createOrReplaceTempView("in_timeseries")

in_timeseries_data_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_timeseries_data_20251225_155101.csv",header=True)
in_timeseries_data_df.createOrReplaceTempView("in_timeseries_data")

in_timeseries_version_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_timeseries_version_20251225_155057.csv",header=True)
in_timeseries_version_df.createOrReplaceTempView("in_timeseries_version")

in_workspace_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\in_workspace_20251225_155056.csv",header=True)
in_workspace_df.createOrReplaceTempView("in_workspace")

sy_account_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\sy_account_20251225_155056.csv",header=True)
sy_account_df.createOrReplaceTempView("sy_account")

sy_app_module_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\sy_app_module_20251225_155056.csv",header=True)
sy_app_module_df.createOrReplaceTempView("sy_app_module")

sy_application_df= spark.read.csv(r"C:\Users\omkar\Desktop\python_practice\zip_assinment_o\sy_application_20251225_155056.csv",header=True)
sy_application_df.createOrReplaceTempView("sy_application")


# Optional: parse datetime column for downstream tasks if needed
# in_timeseries_data = in_timeseries_data.withColumn('dttime', F.to_timestamp('dttime'))


**Q1.** Retrieve all columns from the `sy_account` table.

In [3]:
spark.sql("""
          
SELECT * FROM sy_account

""").show()


+---+-------------------+
| id|               name|
+---+-------------------+
|  2|              Linde|
|  3|              Enpro|
|  4|         Indian Oil|
|  5|Standard Automotive|
|  1|       ESPL_Account|
|  7|           ESPL_UAT|
+---+-------------------+



**Q2.** Find all users from the `ab_user` table where `account_id = 3`.

In [4]:
spark.sql("""
          select * from ab_user
          where account_id=3
          """).show()

+---+--------+----------+
| id|username|account_id|
+---+--------+----------+
|  7|pratik.m|         3|
+---+--------+----------+



**Q3.** Display all application modules from `sy_app_module` ordered by `app_name` in ascending order.

In [5]:
spark.sql("""
          select * from sy_app_module
          order by app_name
          """).show()

+------+--------------+--------+--------------------+
|app_id|application_id|app_code|            app_name|
+------+--------------+--------+--------------------+
|    14|             3|    xsfc|Radar-Demand Plan...|
|     6|             2|    xpnp|        Trinity-S&OP|
|    19|             5|    xbds| XBridge-Integration|
+------+--------------+--------+--------------------+



**Q4.** Fetch the first 10 records from the `in_timeseries_data` table.

In [6]:
spark.sql("""
          select * from in_timeseries_data
          limit 10
          """).show()

+----------+-----+-------------------+---------+----------+
|ts_data_id|ts_id|             dttime|     data|version_id|
+----------+-----+-------------------+---------+----------+
|  44471796|27902|2020-10-01 00:00:00|10549.207|       130|
|  44471774|27902|2018-12-01 00:00:00| 11513.37|       130|
|  44471775|27902|2019-01-01 00:00:00|11556.125|       130|
|  44471776|27902|2019-02-01 00:00:00|11598.547|       130|
|  44471777|27902|2019-03-01 00:00:00|11643.222|       130|
|  44471778|27902|2019-04-01 00:00:00| 11687.96|       130|
|  44471779|27902|2019-05-01 00:00:00|11732.147|       130|
|  44471780|27902|2019-06-01 00:00:00|11775.567|       130|
|  44471781|27902|2019-07-01 00:00:00|11820.099|       130|
|  44471782|27902|2019-08-01 00:00:00|11863.516|       130|
+----------+-----+-------------------+---------+----------+



**Q5.** Count the total number of materials in the `in_material` table for `workspace_id = 53`.

In [7]:
spark.sql("""
       select workspace_id,count(*) AS material_count
from in_material
where workspace_id = 53
group by workspace_id;
""").show()


+------------+--------------+
|workspace_id|material_count|
+------------+--------------+
|          53|            19|
+------------+--------------+



**Q6.** Display all users from `ab_user` ordered by `username` in ascending order.

In [8]:
spark.sql("""
          select * from ab_user 
          order by username 
          """).show()

+---+-----------+----------+
| id|   username|account_id|
+---+-----------+----------+
|  1|      admin|         1|
|  5| customer_1|         1|
|  3|hetal.patel|         1|
|  7|   pratik.m|         3|
|  4|       ravi|         1|
+---+-----------+----------+



**Q7.** Find all timeseries from `in_timeseries` where `workspace_id = 53` and `material_id = 83498`.

In [9]:
spark.sql("""
          select * from in_timeseries
          where material_id=83498
          """).show()

+-----+-----------+------------+-------------+
|ts_id|material_id|geography_id|time_level_id|
+-----+-----------+------------+-------------+
|27803|      83498|       30201|            5|
|27808|      83498|       30202|            5|
|27813|      83498|       30203|            5|
|27818|      83498|       30204|            5|
|27823|      83498|       30205|            5|
|27828|      83498|       30206|            5|
|27363|      83498|       30113|            5|
|27368|      83498|       30114|            5|
|27373|      83498|       30115|            5|
|27378|      83498|       30116|            5|
|27383|      83498|       30117|            5|
|27388|      83498|       30118|            5|
|27393|      83498|       30119|            5|
|27398|      83498|       30120|            5|
|27403|      83498|       30121|            5|
|27408|      83498|       30122|            5|
|27413|      83498|       30123|            5|
|27418|      83498|       30124|            5|
|27423|      

**Q8.** Retrieve all versions from `in_timeseries_version` where `version_id` is 125, 126, or 130.

In [11]:
spark.sql(""" 
          select * from in_timeseries_version
          where version_id  in (125,126,130)
          """).show()

+----------+------------------+-----------+--------------------+
|version_id|      version_name|modified_by|       modified_time|
+----------+------------------+-----------+--------------------+
|       125|               Raw|          1|2022-05-05 13:11:...|
|       126|Manually Corrected|          1|2022-05-05 13:11:...|
|       130|       Forecast-MA|          1|2022-05-11 09:49:...|
+----------+------------------+-----------+--------------------+



**Q9.** Retrieve the first 5 materials from `in_material` where `workspace_id = 53`, ordered by `material_name`.

In [13]:
spark.sql(""" 
          select * from in_material 
where workspace_id=53
order by material_name asc
limit 5
          """).show()

+-----------+-------------+------------+
|material_id|material_name|workspace_id|
+-----------+-------------+------------+
|      83516|          All|          53|
|      83505|    Auto Lube|          53|
|      83504|       Diesel|          53|
|      83509|         Fuel|          53|
|      83503|     Gasoline|          53|
+-----------+-------------+------------+



**Q10.** Count the total number of users in the `ab_user` table.

In [14]:
spark.sql(""" 
          select count(*) as total_users from ab_user 
          """).show()

+-----------+
|total_users|
+-----------+
|          5|
+-----------+



**Q11.** Calculate the sum of all `data` values from the `in_timeseries_data` table where `version_id = 125`.

In [15]:
spark.sql(""" 
          select version_id,sum(data) as sum_data
from in_timeseries_data
where version_id = 125
group by version_id
          """).show()

+----------+--------------------+
|version_id|            sum_data|
+----------+--------------------+
|       125|1.1886324623341472E8|
+----------+--------------------+



**Q12.** Find the average value of `data` from the `in_timeseries_data` table where `workspace_id = 53`.

In [17]:
spark.sql(""" 
          select avg(data) as avg_data from in_timeseries_data
where version_id=125
          """).show()

+------------------+
|          avg_data|
+------------------+
|4571.6633166697975|
+------------------+



**Q13.** Find the maximum and minimum `data` values from the `in_timeseries_data` table where `version_id = 130`.

In [18]:
spark.sql(""" 
          select max(data) as max_data,min(data) as min_data from in_timeseries_data
where version_id=130
          """).show()

+--------+--------+
|max_data|min_data|
+--------+--------+
|959.9358|     0.0|
+--------+--------+



**Q14.** Count the number of timeseries records grouped by `material_id` from the `in_timeseries` table.

In [19]:
spark.sql(""" 
          select material_id,count(*) as count_records from in_timeseries
group by material_id
          """).show()

+-----------+-------------+
|material_id|count_records|
+-----------+-------------+
|      83500|          100|
|      83502|          100|
|      83499|          100|
|      83504|          100|
|      83505|          100|
|      83498|          100|
|      83506|            1|
|      83501|          100|
|      83503|          100|
|      83507|            1|
|      83508|            1|
+-----------+-------------+



**Q15.** Count the number of users grouped by `account_id` where `account_id` is not null.

In [20]:
spark.sql(""" 
          select account_id,count(*) as no_of_users from ab_user 
where account_id is not null
group by account_id
          """).show()

+----------+-----------+
|account_id|no_of_users|
+----------+-----------+
|         1|          4|
|         3|          1|
+----------+-----------+



**Q16.** Display `version_id`, total record count, and average `data` value grouped by `version_id` from `in_timeseries_data` where `workspace_id = 53`.

In [22]:
spark.sql(""" 
          select version_id,count(*) as count_of_records , avg(data) as avd_data from in_timeseries_data
where version_id=130
group by version_id
          """).show()

+----------+----------------+------------------+
|version_id|count_of_records|          avd_data|
+----------+----------------+------------------+
|       130|             234|17071.166381623927|
+----------+----------------+------------------+



**Q17.** Find all `material_id` values that have more than 3 timeseries records.

In [23]:
spark.sql(""" 
          select material_id,count(*) as count from in_timeseries 
group by material_id
having count>1
          """).show()

+-----------+-----+
|material_id|count|
+-----------+-----+
|      83500|  100|
|      83502|  100|
|      83499|  100|
|      83504|  100|
|      83505|  100|
|      83498|  100|
|      83501|  100|
|      83503|  100|
+-----------+-----+



**Q18.** Count the number of timeseries data records grouped by both `version_id` and `ts_id` where `workspace_id = 53`, and show only those with `count > 1`.

In [24]:
spark.sql(""" 
          select version_id,ts_id,count(*) as count_rec from in_timeseries_data
where version_id=125
group by version_id,ts_id
having count_rec >1
          """).show()

+----------+-----+---------+
|version_id|ts_id|count_rec|
+----------+-----+---------+
|       125|27373|       52|
|       125|27375|       52|
|       125|27389|       52|
|       125|27392|       52|
|       125|27419|       52|
|       125|27430|       52|
|       125|27436|       52|
|       125|27438|       52|
|       125|27458|       52|
|       125|27470|       52|
|       125|27474|       52|
|       125|27487|       52|
|       125|27489|       52|
|       125|27490|       52|
|       125|27491|       52|
|       125|27498|       52|
|       125|27507|       52|
|       125|27519|       52|
|       125|27532|       52|
|       125|27534|       52|
+----------+-----+---------+
only showing top 20 rows



**Q19.** Display `username` along with account name. Output columns: `id`, `username`, `account_id`, `name`.

In [25]:
spark.sql(""" 
          select id, username, account_id,name from ab_user
join sy_account 
using (id)
          """).show()

+---+-----------+----------+-------------------+
| id|   username|account_id|               name|
+---+-----------+----------+-------------------+
|  1|      admin|         1|       ESPL_Account|
|  3|hetal.patel|         1|              Enpro|
|  4|       ravi|         1|         Indian Oil|
|  5| customer_1|         1|Standard Automotive|
|  7|   pratik.m|         3|           ESPL_UAT|
+---+-----------+----------+-------------------+



**Q20.** Show all application names and their corresponding application module details. Output columns: `app_id`, `app_code`, `app_name`, `application_id`, `application_name`.

In [26]:
spark.sql(""" 
          select app_id, app_code, app_name, application_id,application_name from sy_app_module
join sy_application 
using (application_id) 
          """).show()

+------+--------+--------------------+--------------+----------------+
|app_id|app_code|            app_name|application_id|application_name|
+------+--------+--------------------+--------------+----------------+
|    19|    xbds| XBridge-Integration|             5|         XBridge|
|    14|    xsfc|Radar-Demand Plan...|             3|          XSight|
|     6|    xpnp|        Trinity-S&OP|             2|           XPlan|
+------+--------+--------------------+--------------+----------------+



**Q21.** Retrieve model names along with their associated application names. Output columns: `model_id`, `model_name`, `application_id`, `application_name`.

In [27]:
spark.sql(""" 
          select model_id, model_name, application_id,application_name from in_model 
join sy_application
using(application_id)
          """).show()

+--------+-----------+--------------+----------------+
|model_id| model_name|application_id|application_name|
+--------+-----------+--------------+----------------+
|      29|Oil and Gas|             3|          XSight|
+--------+-----------+--------------+----------------+



**Q22.** Display workspace names with their corresponding model names. Output columns: `workspace_id`, `workspace_name`, `model_id`, `model_name`.

In [28]:
spark.sql(""" 
          select  workspace_id, workspace_name, model_id,model_name from in_workspace
join in_model
using (model_id)
          """).show()

+------------+--------------+--------+-----------+
|workspace_id|workspace_name|model_id| model_name|
+------------+--------------+--------+-----------+
|          53|        Nayara|      29|Oil and Gas|
+------------+--------------+--------+-----------+



**Q23.** Show all version names along with their workspace names where `workspace_id = 53`. Output columns: `version_id`, `version_name`, `workspace_id`, `workspace_name`.

In [ ]:
spark.sql(""" 
          select v.version_id,v.version_name,w.workspace_id,w.workspace_name
from in_workspace w
cross join in_timeseries_version v
          """).show()

+----------+------------------+------------+--------------+
|version_id|      version_name|workspace_id|workspace_name|
+----------+------------------+------------+--------------+
|       125|               Raw|          53|        Nayara|
|       126|Manually Corrected|          53|        Nayara|
|       130|       Forecast-MA|          53|        Nayara|
|       135|  Forecast-Bestfit|          53|        Nayara|
+----------+------------------+------------+--------------+



**Q24.** Display material names with their workspace names. Output columns: `material_id`, `material_name`, `workspace_id`, `workspace_name`.

In [33]:
spark.sql(""" 
          select material_id, material_name, workspace_id,workspace_name from in_material
join in_workspace
using (workspace_id)
          """).show()

+-----------+-------------+------------+--------------+
|material_id|material_name|workspace_id|workspace_name|
+-----------+-------------+------------+--------------+
|      83515|      LB20W40|          53|        Nayara|
|      83498|       MS Reg|          53|        Nayara|
|      83499|      MS Prem|          53|        Nayara|
|      83500|      HSD Reg|          53|        Nayara|
|      83501|     HSD Prem|          53|        Nayara|
|      83502|Lube20w40 XYZ|          53|        Nayara|
|      83503|     Gasoline|          53|        Nayara|
|      83504|       Diesel|          53|        Nayara|
|      83505|    Auto Lube|          53|        Nayara|
|      83506|      Regular|          53|        Nayara|
|      83507|      Premium|          53|        Nayara|
|      83508|          XYZ|          53|        Nayara|
|      83509|         Fuel|          53|        Nayara|
|      83510|   Lubricants|          53|        Nayara|
|      83511|         MS92|          53|        

**Q25.** Show resource (geography) names along with their workspace names where `workspace_id = 53`. Output columns: `resource_id`, `resource_name`, `workspace_id`, `workspace_name`.

In [36]:
spark.sql(""" 
          select geography_id, resource_name, w.workspace_id,workspace_name from in_resource
join in_workspace as w
using(workspace_id)
where workspace_id= 53
          """).show()

+------------+--------------------+------------+--------------+
|geography_id|       resource_name|workspace_id|workspace_name|
+------------+--------------------+------------+--------------+
|       30113|  Elhaam Corporation|          53|        Nayara|
|       30114| Yashkalgi Petroleum|          53|        Nayara|
|       30115|  Sukhmani Petroleum|          53|        Nayara|
|       30116|Vrajpari Corporation|          53|        Nayara|
|       30117|Sai Shakti Petroleum|          53|        Nayara|
|       30118|           BMF Fuels|          53|        Nayara|
|       30119|       R K Petroleum|          53|        Nayara|
|       30120|    Aastha Petroleum|          53|        Nayara|
|       30121|        JP Petroleum|          53|        Nayara|
|       30122|   UmiyaJi Petroleum|          53|        Nayara|
|       30123|Nilkanth Petroleu...|          53|        Nayara|
|       30124|    Rusabh Petroleum|          53|        Nayara|
|       30125|Nilkanth Petroleu...|     

**Q26.** Display time dimension names with their associated workspace names. Output columns: `time_dimension_id`, `time_dimension_name`, `workspace_id`, `workspace_name`.

In [38]:
spark.sql(""" 
          select time_level_id as time_dimension_id, time_dimension_name, workspace_id,workspace_name  from in_time_dimension
join in_workspace
using(workspace_id)
          """).show()

+-----------------+-------------------+------------+--------------+
|time_dimension_id|time_dimension_name|workspace_id|workspace_name|
+-----------------+-------------------+------------+--------------+
|               64|            Quarter|          53|        Nayara|
|               65|               Year|          53|        Nayara|
|               63|              Month|          53|        Nayara|
+-----------------+-------------------+------------+--------------+



**Q27.** Show timeseries IDs along with their corresponding material names where `workspace_id = 53`. Output columns: `ts_id`, `material_id`, `material_name`, `workspace_id`.

In [41]:
spark.sql(""" 
          select ts_id, m.material_id, material_name,m.workspace_id from in_timeseries as t
join in_material as m
using(material_id)
          """).show()

+-----+-----------+-------------+------------+
|ts_id|material_id|material_name|workspace_id|
+-----+-----------+-------------+------------+
|27803|      83498|       MS Reg|          53|
|27804|      83499|      MS Prem|          53|
|27805|      83500|      HSD Reg|          53|
|27806|      83501|     HSD Prem|          53|
|27807|      83502|Lube20w40 XYZ|          53|
|27808|      83498|       MS Reg|          53|
|27809|      83499|      MS Prem|          53|
|27810|      83500|      HSD Reg|          53|
|27811|      83501|     HSD Prem|          53|
|27812|      83502|Lube20w40 XYZ|          53|
|27813|      83498|       MS Reg|          53|
|27814|      83499|      MS Prem|          53|
|27815|      83500|      HSD Reg|          53|
|27816|      83501|     HSD Prem|          53|
|27817|      83502|Lube20w40 XYZ|          53|
|27818|      83498|       MS Reg|          53|
|27819|      83499|      MS Prem|          53|
|27820|      83500|      HSD Reg|          53|
|27821|      

**Q28.** Display timeseries data along with their version names where `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `version_name`.

In [43]:
spark.sql(""" 
          select ts_data_id, ts_id, dttime, data, version_id,version_name from in_timeseries_data
join in_timeseries_version
using(version_id)
          """).show()

+----------+-----+-------------------+---------+----------+------------+
|ts_data_id|ts_id|             dttime|     data|version_id|version_name|
+----------+-----+-------------------+---------+----------+------------+
|  44471796|27902|2020-10-01 00:00:00|10549.207|       130| Forecast-MA|
|  44471774|27902|2018-12-01 00:00:00| 11513.37|       130| Forecast-MA|
|  44471775|27902|2019-01-01 00:00:00|11556.125|       130| Forecast-MA|
|  44471776|27902|2019-02-01 00:00:00|11598.547|       130| Forecast-MA|
|  44471777|27902|2019-03-01 00:00:00|11643.222|       130| Forecast-MA|
|  44471778|27902|2019-04-01 00:00:00| 11687.96|       130| Forecast-MA|
|  44471779|27902|2019-05-01 00:00:00|11732.147|       130| Forecast-MA|
|  44471780|27902|2019-06-01 00:00:00|11775.567|       130| Forecast-MA|
|  44471781|27902|2019-07-01 00:00:00|11820.099|       130| Forecast-MA|
|  44471782|27902|2019-08-01 00:00:00|11863.516|       130| Forecast-MA|
|  44471783|27902|2019-09-01 00:00:00|11907.183|   

**Q29.** Show all users and their account names where `account_id > 1`. Output columns: `id`, `username`, `account_id`, `name`.

In [44]:
spark.sql(""" 
          select  id, username, account_id,name from ab_user 
join sy_account
using(id)
          """).show()

+---+-----------+----------+-------------------+
| id|   username|account_id|               name|
+---+-----------+----------+-------------------+
|  1|      admin|         1|       ESPL_Account|
|  3|hetal.patel|         1|              Enpro|
|  4|       ravi|         1|         Indian Oil|
|  5| customer_1|         1|Standard Automotive|
|  7|   pratik.m|         3|           ESPL_UAT|
+---+-----------+----------+-------------------+



**Q30.** Display application module names along with their application descriptions. Output columns: `app_id`, `app_name`, `application_id`, `application_name`, `application_description`.

In [45]:
spark.sql(""" 
          select app_id, app_name, application_id, application_name,application_description from sy_app_module
join sy_application
using (application_id)
          """).show()

+------+--------------------+--------------+----------------+-----------------------+
|app_id|            app_name|application_id|application_name|application_description|
+------+--------------------+--------------+----------------+-----------------------+
|    19| XBridge-Integration|             5|         XBridge|   XBridge: Data Eng...|
|    14|Radar-Demand Plan...|             3|          XSight|   XSoght: Predictiv...|
|     6|        Trinity-S&OP|             2|           XPlan|   XPlan: Prescripti...|
+------+--------------------+--------------+----------------+-----------------------+



**Q31.** Show model names and their descriptions along with the application module name. Output columns: `model_id`, `model_name`, `model_description`, `app_id`, `app_name`.

In [46]:
spark.sql(""" 
          select model_id, model_name, model_description,m.app_id,app_name from in_model as m
join sy_app_module
using (application_id)
          """).show()

+--------+-----------+------------------+------+--------------------+
|model_id| model_name| model_description|app_id|            app_name|
+--------+-----------+------------------+------+--------------------+
|      29|Oil and Gas|Oil and Gas Sector|    14|Radar-Demand Plan...|
+--------+-----------+------------------+------+--------------------+



**Q32.** Show workspace name, model name, and application name for `workspace_id = 53`. Output columns: `workspace_id`, `workspace_name`, `model_id`, `model_name`, `application_id`, `application_name`.

In [47]:
spark.sql(""" 
          select workspace_id, workspace_name, model_id, model_name, application_id,application_name from in_workspace
join in_model
using (model_id)
join sy_application
using (application_id)
          """).show()

+------------+--------------+--------+-----------+--------------+----------------+
|workspace_id|workspace_name|model_id| model_name|application_id|application_name|
+------------+--------------+--------+-----------+--------------+----------------+
|          53|        Nayara|      29|Oil and Gas|             3|          XSight|
+------------+--------------+--------+-----------+--------------+----------------+



**Q33.** Display timeseries ID, material name, geography name, and time dimension name for `workspace_id = 53`. Output columns: `ts_id`, `material_id`, `material_name`, `resource_id`, `resource_name`, `time_dimension_id`, `time_dimension_name`.

In [59]:
spark.sql(""" 
          select  td.ts_id, m.material_id, material_name, r.geography_id as resource_id, resource_name as geography_name ,td.time_level_id,time_dimension_name from in_material as m
join in_resource as r
using(workspace_id)
join in_timeseries
using(material_id)
join in_timeseries_data as td
using (ts_id)
join in_time_dimension as td
using(workspace_id)
          """).show()

+-----+-----------+-------------+-----------+------------------+-------------+-------------------+
|ts_id|material_id|material_name|resource_id|    geography_name|time_level_id|time_dimension_name|
+-----+-----------+-------------+-----------+------------------+-------------+-------------------+
|27904|      83508|          XYZ|      30113|Elhaam Corporation|           63|              Month|
|27904|      83508|          XYZ|      30113|Elhaam Corporation|           65|               Year|
|27904|      83508|          XYZ|      30113|Elhaam Corporation|           64|            Quarter|
|27904|      83508|          XYZ|      30113|Elhaam Corporation|           63|              Month|
|27904|      83508|          XYZ|      30113|Elhaam Corporation|           65|               Year|
|27904|      83508|          XYZ|      30113|Elhaam Corporation|           64|            Quarter|
|27904|      83508|          XYZ|      30113|Elhaam Corporation|           63|              Month|
|27904|   

**Q34.** Display timeseries data value, material name, geography name, and version name where `workspace_id = 53` and `version_id = 125`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `material_id`, `material_name`, `resource_id`, `resource_name`, `version_id`, `version_name`.

In [69]:
spark.sql(""" 
          select  ts_data_id, ts_id, dttime, data, material_id, material_name,geography_id as resource_id, resource_name, version_id,version_name 
          from in_timeseries_data
          join in_timeseries_version
          using (version_id)
          cross join in_material as m
          join in_resource
          using (workspace_id)
          where m.workspace_id=53 and version_id=125
          """).show()

+----------+-----+-------------------+---------+-----------+-------------+-----------+--------------+----------+------------+
|ts_data_id|ts_id|             dttime|     data|material_id|material_name|resource_id| resource_name|version_id|version_name|
+----------+-----+-------------------+---------+-----------+-------------+-----------+--------------+----------+------------+
|  43177824|27364|2019-04-01 00:00:00|381.43152|      83515|      LB20W40|      30241|       Bhiwadi|       125|         Raw|
|  43177824|27364|2019-04-01 00:00:00|381.43152|      83515|      LB20W40|      30240|          Kota|       125|         Raw|
|  43177824|27364|2019-04-01 00:00:00|381.43152|      83515|      LB20W40|      30239|       Jodhpur|       125|         Raw|
|  43177824|27364|2019-04-01 00:00:00|381.43152|      83515|      LB20W40|      30238|        Jaipur|       125|         Raw|
|  43177824|27364|2019-04-01 00:00:00|381.43152|      83515|      LB20W40|      30237|         Akola|       125|      

**Q35.** Show the latest 10 timeseries records (by datetime descending) for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `material_name`, `resource_name`, `time_dimension_name`, `version_name`, `workspace_name`.

In [72]:
spark.sql(""" 
          select ts_data_id, ts_id, dttime, data, material_name, resource_name as geography_name, time_dimension_name, version_name,workspace_name
          from in_timeseries_data
        cross join in_material
        join in_resource
        using(workspace_id)
        join in_time_dimension
        using(workspace_id)
        join in_workspace
        using(workspace_id)
        join in_timeseries_version
        using(version_id) 
        where workspace_id=53
          """).show()

+----------+-----+-------------------+---------+-------------+--------------+-------------------+------------+--------------+
|ts_data_id|ts_id|             dttime|     data|material_name|geography_name|time_dimension_name|version_name|workspace_name|
+----------+-----+-------------------+---------+-------------+--------------+-------------------+------------+--------------+
|  44471796|27902|2020-10-01 00:00:00|10549.207|      LB20W40|       Bhiwadi|              Month| Forecast-MA|        Nayara|
|  44471796|27902|2020-10-01 00:00:00|10549.207|      LB20W40|       Bhiwadi|               Year| Forecast-MA|        Nayara|
|  44471796|27902|2020-10-01 00:00:00|10549.207|      LB20W40|       Bhiwadi|            Quarter| Forecast-MA|        Nayara|
|  44471796|27902|2020-10-01 00:00:00|10549.207|      LB20W40|          Kota|              Month| Forecast-MA|        Nayara|
|  44471796|27902|2020-10-01 00:00:00|10549.207|      LB20W40|          Kota|               Year| Forecast-MA|        

**Q36.** Assign a row number to each timeseries data record within `version_id =125`, ordered by `dttime`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `row_num`.

In [78]:
spark.sql(""" 
          select ts_data_id, ts_id, dttime, data, version_id,
		row_number() over(order by dttime asc)as row_num from in_timeseries_data
where version_id=125
          """).show()

+----------+-----+-------------------+----------+----------+-------+
|ts_data_id|ts_id|             dttime|      data|version_id|row_num|
+----------+-----+-------------------+----------+----------+-------+
|  43179600|27398|2018-01-01 00:00:00|  71.55379|       125|      1|
|  43180659|27419|2018-01-01 00:00:00|   36.3825|       125|      2|
|  43179704|27400|2018-01-01 00:00:00|  99.41498|       125|      3|
|  43178157|27371|2018-01-01 00:00:00|  2901.168|       125|      4|
|  43179756|27401|2018-01-01 00:00:00| 11.840634|       125|      5|
|  43178002|27368|2018-01-01 00:00:00| 18240.324|       125|      6|
|  43179807|27402|2018-01-01 00:00:00| 1.4639626|       125|      7|
|  43178320|27374|2018-01-01 00:00:00| 2324.7139|       125|      8|
|  43179867|27403|2018-01-01 00:00:00|10414.8545|       125|      9|
|  43178535|27378|2018-01-01 00:00:00| 25692.166|       125|     10|
|  43179918|27404|2018-01-01 00:00:00| 1280.0442|       125|     11|
|  43178690|27381|2018-01-01 00:00

**Q37.** Rank timeseries data values within each `version_id=125` ordered by `data` value descending. Output columns: `ts_data_id`, `ts_id`, `data`, `version_id`, `rank`.

In [82]:
spark.sql(""" 
          select ts_data_id, ts_id, data, version_id,
		rank() over(order by data desc) as rk from in_timeseries_data
where version_id=125
          """).show()

+----------+-----+--------+----------+---+
|ts_data_id|ts_id|    data|version_id| rk|
+----------+-----+--------+----------+---+
|  43194636|27688|9999.566|       125|  1|
|  43198580|27763|9998.707|       125|  2|
|  43194157|27678|9997.176|       125|  3|
|  43193960|27675|9996.405|       125|  4|
|  43182558|27455|9994.589|       125|  5|
|  43187743|27555|999.3399|       125|  6|
|  43192580|27648|9987.178|       125|  7|
|  43192446|27645|9986.819|       125|  8|
|  43202025|27830| 9986.42|       125|  9|
|  43194923|27693|9985.631|       125| 10|
|  43198816|27768|9983.248|       125| 11|
|  43189566|27590|9982.525|       125| 12|
|  43181745|27440|9981.848|       125| 13|
|  43196601|27725|9980.734|       125| 14|
|  43191404|27625|9978.993|       125| 15|
|  43197542|27743|9978.085|       125| 16|
|  43192576|27648| 9977.19|       125| 17|
|  43194008|27675|9976.452|       125| 18|
|  43187477|27550|9974.119|       125| 19|
|  43185948|27520|9973.939|       125| 20|
+----------

**Q38.** Calculate the running total (cumulative sum) of `data` values for each `ts_id`, ordered by `dttime`, for `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `running_total`.

In [84]:
spark.sql(""" 
          select ts_data_id, ts_id, dttime, data, version_id,
		sum(data) over(order by dttime) as running_total from in_timeseries_data
where version_id=125
          """).show()

+----------+-----+-------------------+---------+----------+---------------+
|ts_data_id|ts_id|             dttime|     data|version_id|  running_total|
+----------+-----+-------------------+---------+----------+---------------+
|  43177787|27363|2018-01-01 00:00:00|2915.9478|       125|2818629.7203409|
|  43177995|27367|2018-01-01 00:00:00|58.944374|       125|2818629.7203409|
|  43178002|27368|2018-01-01 00:00:00|18240.324|       125|2818629.7203409|
|  43178157|27371|2018-01-01 00:00:00| 2901.168|       125|2818629.7203409|
|  43178268|27373|2018-01-01 00:00:00|19071.441|       125|2818629.7203409|
|  43178320|27374|2018-01-01 00:00:00|2324.7139|       125|2818629.7203409|
|  43178424|27376|2018-01-01 00:00:00|3224.8557|       125|2818629.7203409|
|  43178535|27378|2018-01-01 00:00:00|25692.166|       125|2818629.7203409|
|  43178586|27379|2018-01-01 00:00:00|3095.1455|       125|2818629.7203409|
|  43178690|27381|2018-01-01 00:00:00| 4009.496|       125|2818629.7203409|
|  43178742|

**Q39.** Find the previous and next `data` values for each timeseries record ordered by `dttime`, where `workspace_id = 53` and `version_id = 125`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `previous_value`, `next_value`.

In [86]:
spark.sql(""" 
          select ts_data_id, ts_id, dttime, data, 
		lag(data) over(order by dttime) as previous_value,
        lead(data)over(order by dttime) as next_value from in_timeseries_data
where version_id=125
          """).show()

+----------+-----+-------------------+---------+--------------+----------+
|ts_data_id|ts_id|             dttime|     data|previous_value|next_value|
+----------+-----+-------------------+---------+--------------+----------+
|  43177787|27363|2018-01-01 00:00:00|2915.9478|          NULL| 58.944374|
|  43177995|27367|2018-01-01 00:00:00|58.944374|     2915.9478| 18240.324|
|  43178002|27368|2018-01-01 00:00:00|18240.324|     58.944374|  2901.168|
|  43178157|27371|2018-01-01 00:00:00| 2901.168|     18240.324| 19071.441|
|  43178268|27373|2018-01-01 00:00:00|19071.441|      2901.168| 2324.7139|
|  43178320|27374|2018-01-01 00:00:00|2324.7139|     19071.441| 3224.8557|
|  43178424|27376|2018-01-01 00:00:00|3224.8557|     2324.7139| 25692.166|
|  43178535|27378|2018-01-01 00:00:00|25692.166|     3224.8557| 3095.1455|
|  43178586|27379|2018-01-01 00:00:00|3095.1455|     25692.166|  4009.496|
|  43178690|27381|2018-01-01 00:00:00| 4009.496|     3095.1455|   501.187|
|  43178742|27382|2018-01

**Q40.** Calculate the moving average of `data` values over the last 3 records (including current) for each timeseries ordered by `dttime`, where `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `moving_avg_3`.

In [88]:
spark.sql(""" 
          select ts_data_id, ts_id, dttime, data,
		avg(data) over (order by dttime rows between 2 preceding and current row) as moving_avg_3 from in_timeseries_data
where version_id=125
          """).show()

+----------+-----+-------------------+---------+------------------+
|ts_data_id|ts_id|             dttime|     data|      moving_avg_3|
+----------+-----+-------------------+---------+------------------+
|  43177787|27363|2018-01-01 00:00:00|2915.9478|         2915.9478|
|  43177995|27367|2018-01-01 00:00:00|58.944374|       1487.446087|
|  43178002|27368|2018-01-01 00:00:00|18240.324| 7071.738724666667|
|  43178157|27371|2018-01-01 00:00:00| 2901.168| 7066.812124666667|
|  43178268|27373|2018-01-01 00:00:00|19071.441|13404.311000000002|
|  43178320|27374|2018-01-01 00:00:00|2324.7139| 8099.107633333333|
|  43178424|27376|2018-01-01 00:00:00|3224.8557| 8207.003533333333|
|  43178535|27378|2018-01-01 00:00:00|25692.166|10413.911866666667|
|  43178586|27379|2018-01-01 00:00:00|3095.1455|        10670.7224|
|  43178690|27381|2018-01-01 00:00:00| 4009.496|10932.269166666667|
|  43178742|27382|2018-01-01 00:00:00|  501.187|2535.2761666666665|
|  43178853|27384|2018-01-01 00:00:00|111.46248|

**Q41.** Assign a dense rank to materials based on the count of their timeseries records in `workspace_id = 53`. Output columns: `material_id`, `timeseries_count`, `dense_rank`.

In [94]:
spark.sql(""" 
          select material_id,
		count(*) over(partition by workspace_id) as  timeseries_count,
		dense_rank() over(order by material_id) as dense_rank from in_material
where workspace_id=53
          """).show()

+-----------+----------------+----------+
|material_id|timeseries_count|dense_rank|
+-----------+----------------+----------+
|      83498|              19|         1|
|      83499|              19|         2|
|      83500|              19|         3|
|      83501|              19|         4|
|      83502|              19|         5|
|      83503|              19|         6|
|      83504|              19|         7|
|      83505|              19|         8|
|      83506|              19|         9|
|      83507|              19|        10|
|      83508|              19|        11|
|      83509|              19|        12|
|      83510|              19|        13|
|      83511|              19|        14|
|      83512|              19|        15|
|      83513|              19|        16|
|      83514|              19|        17|
|      83515|              19|        18|
|      83516|              19|        19|
+-----------+----------------+----------+



**Q42.** Partition timeseries data by `version_id` and display the maximum `data` value within each version for `version_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`, `max_in_version`.

In [96]:
spark.sql(""" 
          select ts_data_id, ts_id, dttime, data, version_id,
		max(data) over(partition by version_id) as max_in_version from in_timeseries_data
where version_id=125
          """).show()

+----------+-----+-------------------+---------+----------+--------------+
|ts_data_id|ts_id|             dttime|     data|version_id|max_in_version|
+----------+-----+-------------------+---------+----------+--------------+
|  43177824|27364|2019-04-01 00:00:00|381.43152|       125|      9999.566|
|  43177754|27363|2020-10-01 00:00:00|2041.8203|       125|      9999.566|
|  43177755|27363|2020-09-01 00:00:00| 1921.837|       125|      9999.566|
|  43177756|27363|2020-08-01 00:00:00|1991.6937|       125|      9999.566|
|  43177757|27363|2020-07-01 00:00:00|1933.8904|       125|      9999.566|
|  43177758|27363|2020-06-01 00:00:00|1984.3469|       125|      9999.566|
|  43177759|27363|2020-05-01 00:00:00|1891.3866|       125|      9999.566|
|  43177760|27363|2020-04-01 00:00:00|1829.2837|       125|      9999.566|
|  43177761|27363|2020-03-01 00:00:00|2682.4043|       125|      9999.566|
|  43177762|27363|2020-02-01 00:00:00| 2533.259|       125|      9999.566|
|  43177763|27363|2020-01

**Q43.** Calculate the percentage contribution of each `data` value to the total sum of its version for `version_id = 53`. Output columns: `ts_data_id`, `ts_id`, `data`, `version_id`, `percentage_of_total`.

In [99]:
spark.sql(""" 
          select ts_data_id, ts_id, data, version_id, 
		 (data / SUM(data) OVER ()) * 100 AS percentage_of_total from in_timeseries_data
where version_id=125
          """).show()

+----------+-----+---------+----------+--------------------+
|ts_data_id|ts_id|     data|version_id| percentage_of_total|
+----------+-----+---------+----------+--------------------+
|  43177824|27364|381.43152|       125|3.208994639528634E-4|
|  43177754|27363|2041.8203|       125|0.001717789446866045|
|  43177755|27363| 1921.837|       125|0.001616847142325...|
|  43177756|27363|1991.6937|       125|0.001675617790287...|
|  43177757|27363|1933.8904|       125|0.001626987703332...|
|  43177758|27363|1984.3469|       125|0.001669436905755...|
|  43177759|27363|1891.3866|       125|0.001591229130900...|
|  43177760|27363|1829.2837|       125|0.001538981777771566|
|  43177761|27363|2682.4043|       125| 0.00225671465739081|
|  43177762|27363| 2533.259|       125|0.002131238276149...|
|  43177763|27363|2597.7861|       125|0.002185525115895508|
|  43177764|27363|2419.9697|       125|0.002035927653572447|
|  43177765|27363|2399.9453|       125|0.002019081066730...|
|  43177766|27363|2397.4

**Q44.** Find the first and last `data` values for each `ts_id` ordered by `dttime`, where `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `first_value`, `last_value`.

In [106]:
spark.sql(""" 
          SELECT ts_data_id,ts_id,dttime, data,
    FIRST_VALUE(data) OVER (PARTITION BY ts_id ORDER BY dttime ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS first_value,
    LAST_VALUE(data) OVER ( PARTITION BY ts_id ORDER BY dttime ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_value
FROM in_timeseries_data
WHERE version_id = 125
ORDER BY ts_id, dttime
          """).show()

+----------+-----+-------------------+---------+-----------+----------+
|ts_data_id|ts_id|             dttime|     data|first_value|last_value|
+----------+-----+-------------------+---------+-----------+----------+
|  43177787|27363|2018-01-01 00:00:00|2915.9478|  2915.9478|  2055.375|
|  43177786|27363|2018-02-01 00:00:00|2846.3586|  2915.9478|  2055.375|
|  43177785|27363|2018-03-01 00:00:00|3013.9375|  2915.9478|  2055.375|
|  43177784|27363|2018-04-01 00:00:00|2057.4304|  2915.9478|  2055.375|
|  43177783|27363|2018-05-01 00:00:00| 2129.408|  2915.9478|  2055.375|
|  43177782|27363|2018-06-01 00:00:00| 2225.144|  2915.9478|  2055.375|
|  43177781|27363|2018-07-01 00:00:00|2172.9106|  2915.9478|  2055.375|
|  43177780|27363|2018-08-01 00:00:00|2237.8582|  2915.9478|  2055.375|
|  43177779|27363|2018-09-01 00:00:00|2159.3674|  2915.9478|  2055.375|
|  43177778|27363|2018-10-01 00:00:00|2294.1802|  2915.9478|  2055.375|
|  43177777|27363|2018-11-01 00:00:00|2296.5984|  2915.9478|  20

**Q45.** Calculate the difference between each `data` value and the average `data` value within its version for `version_id =125`. Output columns: `ts_data_id`, `ts_id`, `data`, `version_id`, `avg_in_version`, `difference_from_avg`.

In [108]:
spark.sql(""" 
          select ts_data_id,ts_id,data,version_id,
    avg(data) over (partition by version_id) as avg_in_version,
    data - avg(data) over (partition by version_id) as difference_from_avg
from in_timeseries_data
where version_id =125
order by version_id, ts_data_id
          """).show()

+----------+-----+---------+----------+------------------+-------------------+
|ts_data_id|ts_id|     data|version_id|    avg_in_version|difference_from_avg|
+----------+-----+---------+----------+------------------+-------------------+
|  43177736|27363| 2055.375|       125|4571.6633166697975|-2516.2883166697975|
|  43177737|27363|3022.9883|       125|4571.6633166697975|-1548.6750166697975|
|  43177738|27363|2854.9062|       125|4571.6633166697975|-1716.7571166697976|
|  43177739|27363|2915.9478|       125|4571.6633166697975|-1655.7155166697976|
|  43177740|27363| 2147.203|       125|4571.6633166697975|-2424.4603166697975|
|  43177741|27363|2137.9722|       125|4571.6633166697975|-2433.6911166697973|
|  43177742|27363| 2142.139|       125|4571.6633166697975|-2429.5243166697974|
|  43177743|27363|2002.1992|       125|4571.6633166697975|-2569.4641166697975|
|  43177744|27363| 2081.208|       125|4571.6633166697975|-2490.4553166697974|
|  43177745|27363|2014.7565|       125|4571.66331666

**Q46.** Rank materials by their total `data` sum across all timeseries in `workspace_id = 53`. Output columns: `material_id`, `material_name`, `total_data_sum`, `rank`.

In [111]:
spark.sql(""" 
          select m.material_id,m.material_name,
	sum(td.data) as total_data_sum,
    rank() over (order by sum(td.data) desc) as rk
from in_timeseries_data td
join in_timeseries ts
using(ts_id)
join in_material m
using (material_id)
where m.workspace_id = 53
group by m.material_id, m.material_name
order by total_data_sum desc
          """).show()

+-----------+-------------+-------------------+---+
|material_id|material_name|     total_data_sum| rk|
+-----------+-------------+-------------------+---+
|      83500|      HSD Reg|5.789560762242195E7|  1|
|      83498|       MS Reg|4.464722608354395E7|  2|
|      83501|     HSD Prem|  8706304.853283972|  3|
|      83499|      MS Prem|  6524663.734419964|  4|
|      83506|      Regular| 3441099.7019999996|  5|
|      83502|Lube20w40 XYZ| 1089443.9397443978|  6|
|      83507|      Premium|  516862.8430999999|  7|
|      83508|          XYZ|  36690.38820000001|  8|
+-----------+-------------+-------------------+---+



**Q47.** Display all timeseries data records where the `data` value is greater than the average `data` value across all records in `workspace_id = 53`. Output columns: `ts_data_id`, `ts_id`, `dttime`, `data`, `version_id`.

In [112]:
spark.sql(""" 
          select ts_data_id,ts_id,dttime,data,version_id
from (select ts_data_id,ts_id,dttime,data,version_id,
	avg(data) over () as avg_data_all from in_timeseries_data
    where version_id =125) as t
where data > avg_data_all
order by dttime
          """).show()

+----------+-----+-------------------+---------+----------+
|ts_data_id|ts_id|             dttime|     data|version_id|
+----------+-----+-------------------+---------+----------+
|  43182458|27453|2018-01-01 00:00:00|10262.908|       125|
|  43178638|27380|2018-01-01 00:00:00|32807.934|       125|
|  43182561|27455|2018-01-01 00:00:00|13773.989|       125|
|  43178268|27373|2018-01-01 00:00:00|19071.441|       125|
|  43182721|27458|2018-01-01 00:00:00|5465.4854|       125|
|  43178535|27378|2018-01-01 00:00:00|25692.166|       125|
|  43182825|27460|2018-01-01 00:00:00|6968.7466|       125|
|  43180341|27413|2018-01-01 00:00:00| 6220.953|       125|
|  43182984|27463|2018-01-01 00:00:00|15175.523|       125|
|  43179970|27405|2018-01-01 00:00:00|14683.716|       125|
|  43183088|27465|2018-01-01 00:00:00|20753.828|       125|
|  43180231|27410|2018-01-01 00:00:00|12063.957|       125|
|  43183247|27468|2018-01-01 00:00:00| 22413.83|       125|
|  43180874|27423|2018-01-01 00:00:00| 6

**Q48.** Find the material with the maximum number of timeseries records in `workspace_id = 53`. Output columns: `material_id`, `material_name`, `timeseries_count`.

In [114]:
spark.sql(""" 
          select m.material_id,m.material_name,
    count(ts.ts_id) as timeseries_count
from in_timeseries ts
join in_material m
using (material_id)
where m.workspace_id = 53
group by m.material_id, m.material_name
order by timeseries_count desc
limit 1
          """).show()

+-----------+-------------+----------------+
|material_id|material_name|timeseries_count|
+-----------+-------------+----------------+
|      83503|     Gasoline|             100|
+-----------+-------------+----------------+



# -------------------------------------------------------------------------